### ISSUE TITLE
Log spam while in water in various states

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#401] opened 2015-09-21 01:20 UTC
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

---

If you dive-prone into a water volume it'll spam log, this should not happen unless the volume has bWaterVolume = true in it.  The DH_WaterVolume has this set to false by default, but in some cases of deep water will set it to true.

Other scenarios and states should be checked as well. 

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/402

**Comment by AndrewTheel** [comment] 2016-05-19 19:20
These may get fixed with MattUK's changes, so I'll assign this to him.

**Comment by handsm** [comment] 2016-06-09 22:32
Is the log spam something like this?
Log: PlayAnim: Sequence 'None' not found for mesh 'USWinter_GI'

**Comment by AndrewTheel** [comment] 2016-06-14 11:45
Yea I think so

**Comment by handsm** [comment] 2016-10-29 15:17
Just a quick bump to get my own attention!

**Comment by handsm** [comment] 2017-01-08 17:35
Just a quick bump to get my own attention!

**Comment by handsm** [comment] 2017-02-04 13:40
Believe it was caused by a pawn animation property called IdleSwimAnim that has no specified anim. It's not used anywhere in script so must be used in native movement animation code. I tested by specifying a nonsense anim name in DHPawn's def props and the log error reported it was trying to play that non-existent anim instead of just 'none'.

In ROPawn there is an array of 4 directional SwimAnims, which have specified anims ('stand_jogX_nade'). The IdleSwimAnim must be the idle counterpart to those.

The equivalent idle anim is 'stand_idlehip_nade', so I have specified that as the IdleSwimAnim in DHPawn.

Don't think this is anything specifically related to dive prone; expect it would have spammed log errors whenever 'standing' still in the swimming state. I guess you would notice the error after dive proning because you would be still for a moment, where more usually you run or walk into water and because you were moving you wouldn't get the log errors.

Should be fixed in commit https://github.com/DarklightGames/DarkestHour/commit/2bba9a5bd67503149b025bda8223754b6d543073.

**Closed by handsm** 2017-02-04 13:40 UTC
Labels: bug, miscellaneous
