### ISSUE TITLE
Map vote list cannot be sorted by the current vote count

### ISSUE THREAD

**Issue by clad** [DarklightGames/DarkestHour#591] opened 2016-08-09 21:17 UTC
Clicking on 'votes' column does not sort by votes (or it is combining sort options in an unexpected way).

**Comment by cmbasnett** [comment] 2016-08-18 05:02
The problem is in `DHMapVoteCountMultiColumnList.GetSortString`. The whole scheme the default list sort logic is absurd. It allows the the previously selected sort column to influence the sorting, which can have a bizarre effect. Furthermore, it appears to **only** take the name of the map into consideration. I will sort this out (pun intended).

**Comment by AndrewTheel** [comment] 2016-08-18 17:00
Yea I don't understand sorting, please do.

**Comment by AndrewTheel** [comment] 2016-09-27 18:57
Fixed in commit 5d31ac4

**Closed by AndrewTheel** 2016-09-27 18:57 UTC
Labels: bug, interface
