### ISSUE TITLE
Tankers whose tank is immobilized should be able to scuttle their tank

### ISSUE THREAD

**Issue by kashash** [DarklightGames/DarkestHour#731] opened 2017-07-10 16:26 UTC
Tankers whose tank is immobilized should be able to scuttle their tank instead of asking the team to bring a panzerschreck and blow it up.

**Comment by handsm** [comment] 2017-07-10 18:44
I think probably a good idea.

@kashash : how do you see the player doing it, i.e. by what key press, menu option, or whatever?>

**Comment by kashash** [comment] 2017-07-10 18:59
Maybe the Throw weapon key could be used for the scuttle the tank. You never throw weapons when you're inside the tank, however the "throw weapon" key kinda represents as if you're throwing the tank away so yea the "throw weapon" key could be used.

**Comment by cmbasnett** [comment] 2017-07-10 19:05
If we implement this, there should be a confirmation prompt using some sort of `DHPromptInteraction`, just so people don't accidentally hit the button and then destroy their tanks. This could set a scuttle timer (eg. 10 seconds until it blows up) simply set the engine on fire and then let it spread and it will eventually die. To stop griefing, it might be a good idea to think of some restrictions to this working. For example, a tank might need to have some irreparable damage before it can be scuttled (eg. tread destroyed, engine destroyed, gunsight damaged etc.).

**Comment by kashash** [comment] 2017-07-10 19:07
Yes agreed, although would be nice to scuttle the tanks even if they are not damaged because they often get stuck as well and often no anti-tank is nearby to destroy it.

**Comment by AndrewTheel** [comment] 2017-07-10 19:27
If we do scuttle vehicles, then it needs to be possible to do on health vehicles.  Straight up it is not worth doing IMO unless we can do it on healthy vehicles.

It should definitely not be instant.  However, I might have another solution for stuck vehicles.

The idea is simple.  If your vehicle is stuck, shut off the engine, and type or hit command "/stuck" or something.  After 15 seconds if the engine is still off (meaning the vehicle hasn't moved) it'll throw the vehicle up a bit (to hopefully get it unstuck).  It doesn't have to be much, just like a foot or so high.  The engine has to be off to indicate to the game the vehicle isn't being driven and the 15 second delay is so it can't be abused.

**Comment by handsm** [comment] 2017-07-10 19:27
Note that when a tank (or any vehicle) has some irreparable damage it sets a 'spike timer' when the last occupant gets out, which blows up the tank after a set period, providing it is still empty at that time. The time is determined by the vehicle's VehicleSpikeTime setting. That can be set per vehicle, but it defaults to 60 seconds for an armoured vehicle or 30 seconds for others.

**Comment by kashash** [comment] 2017-07-10 19:33
I would prefer if we removed theVehicleSpikeTime when the tank is damaged because I sometimes when the tank is immobilized I still use it as a "bunker" if it's in a good spot, and I wouldn't want having it all of sudden destroyed just because I left it empty for 30-60 seconds. If I wanted to destroy my tank I would just scuttle it, this is why scuttling is better.

**Comment by cmbasnett** [comment] 2017-07-10 19:49
Here's an idea: to stop greifers, scuttles could be "cancelled" if someone re-enters the vehicle. When a scuttle is initiated, it pops the dude out of the tank; if it is ever re-entered by anyone with permission, the scuttle is cancelled.

**Comment by handsm** [comment] 2017-07-10 19:52
Agree, the scuttle should act like the spike timer in that it automatically gets cancelled if anyone gets back in.

Kash - I guess scuttling could replace the spike timer, although it could cause the team a problem if a player fails to do so and just wanders off, or is killed nearby. But if you have an immobilised tank that you use as a bunker, the spike timer won't be relevant, will it? 60 seconds is a long time away from a tank that's being used as a bunker. Seems like fair game for the game to assume it's been abandoned at that point. The spike timer only begins when/if you leave the vehicle and it's empty.

**Comment by AndrewTheel** [comment] 2017-07-10 20:01
The vehicle must be empty to initiate a scuttle.

**Comment by kashash** [comment] 2017-07-11 06:05
Yea I was actually thinking of a scenario where the tanker gets out of the tank and gets killed so as long as the spike timer is long enough for the tanker to roam about outside the tank and leave it empty without suddenly getting exploded.

**Comment by NathanBLewis** [comment] 2017-07-12 12:51
Why not add a repair kit for the tanks, sounds like a better idea, cause even after they "scuttle" the tank, the tankers themselves will still be inclined to die to respawn another tank...

**Comment by cmbasnett** [comment] 2017-07-13 19:46
@NathanBLewis I think if we were going to do something like this we would have a "vehicle repair station" construction that a tank would have to hobble back to and sit there to repair any "critical" damage (gunsights not working, engine working at half-power, turret jammed etc.). It's not on the docket to do for phase 1, but it can be kept in mind for a future release, depending on how @handsm feels about this. :P

**Comment by NathanBLewis** [comment] 2017-07-16 12:24
vehicle repair station is a great idea actually

**Comment by kashash** [comment] 2017-07-21 09:16
I think that the vehicle repair station might possibly be too gamey for DH, and also most of the times when the tank is damaged, it's immobilized at the same time so how it would ever manage to go to a repair station, it would probably be a bit too arcade. It's better if the tankers just respawn with another tank really... And the ability to scuttle the tank would greatly speed things up instead of asking the team to bring a panzerschreck...

**Comment by AndrewTheel** [comment] 2017-09-15 12:45
Okay so part of my idea with this: https://github.com/DarklightGames/DarkestHour/pull/767
Is that all vehicles can be set on fire and take damage over time when on fire. However, if the vehicle doesn't shoot and is manned the fire will go out after so many seconds (thinking 10-15 seconds). This is a great idea, because it fulfills many ideas regarding gameplay and vehicle fire. For example, if a tank is set on fire with AT it can remain shooting at the enemy, but it will burn to death doing so.  Or it can retreat to cover and extinguish the flames and then return to the fight.

Another awesome part of that idea is all we need to do to "scuttle" a vehicle is have the user set it on fire. The check is simple, is the vehicle owned by this individual and is the vehicle clear of occupants.  

This system is also cancel-able as if another player enters the vehicle on fire (which we will have to change again) they can "extinguish" the fire.

**Comment by cmbasnett** [comment] 2017-09-17 09:05
I don't believe this will be ready (or would be able to be implemented properly) for 8.0, so I'm taking it off of the 8.0 milestone. We can revisit it for 8.x.

**Comment by AndrewTheel** [comment] 2019-01-23 07:31
Duplicate of https://github.com/DarklightGames/DarkestHour/issues/907

**Closed by AndrewTheel** 2019-01-23 07:31 UTC
Labels: design, enhancement, gameplay, suggestion, task, vehicles
