### ISSUE TITLE
RPG-43 grenades sometimes do not play explosion effects despite actually exploding

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#662] opened 2017-02-21 06:56 UTC
Happened during testing. About 1 in 4 times the explosion effect won't spawn.

**Comment by handsm** [comment] 2017-02-21 14:22
Have fix - just tidying up.

**Comment by handsm** [comment] 2017-02-21 15:57
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/7f8269a57f2a737690139e30c06e34d405f79f3a.

Problem was caused by some of the inherited cannon shell functionality (RPG-43 extends cannon shell HEAT, to make use of HEAT functionality). Because a shell is fully replicated (i.e. not a net temporary, torn off actor), when the server version explodes it waits 0.2 seconds to give the client time to catch up before destroying the actor, which causes it to be destroyed on the client. If the client doesn't catch up, i.e. detect its own collision & play explosion effects locally, when the actor is destroyed by the server its Destroyed() event plays explosion effects.

But unlike other grenades or shells, the RPG-43 doesn't always explode. The actor gets 'quietly' destroyed if it lands without detonating. So to stop that causing unwanted explosion effects it had bDidExplosionFX=true in default properties, so by default explosion effects were disabled. Then if the grenade did detonate on impact, bDidExplosionFX was actively changed to false so that explosion effects would play.

The problem was that didn't work with the inherited cannon shell system, when the client failed to catch up and explode before the server destroyed the actor. The Destroyed() event was prevented from playing explosion effects because bDidExplosionFX was true by default. It required the client to trigger its own explosion in order to switch bDidExplosionFX to false and then explode.

I've now removed unnecessary and unwanted stuff from the cannon shell:

1) Made the RPG-43 a net temporary, torn off actor. Grenades are fully replicated, but only because they are destroyed by a fuze timer, which the server has to control. This one doesn't need to be fully replicated and can be torn off when it spawns.

2) Removed the cannon shell functionality about delayed destruction and explosion effects being played in Destroyed(). The client actor is now independent of the server and will always handle its own explosion and destruction.

3) Removed the bDidExplosionFX stuff, which is no longer required or relevant.

This is a clean solution (actually a little cleaner than before). And it's a bit more network efficient, since the actor is no longer replicated after it spawns, meaning one less net channel during its life.

Interestingly, I could not recreate this problem in a bad network environment. I usually do server tests in bad conditions - high ping and some packet loss and duplication. Threw hundreds of these things, never a problem. Only saw the problem when I switched to a no lag setup, where I get very low pings. I guess its because in bad conditions the delay in my client receiving the destroy signal down the net channel from the server means my client has time to do its own explosion. So some multiplayer problems only show up with low ping; quite a few I expect. I think if I was playing for real on a US server, I wouldn't have seen this problem, due to my higher ping.

**Closed by handsm** 2017-02-21 15:57 UTC
Labels: bug
