### ISSUE TITLE
UnrealPlayerChatManager.GetIDIndex Runaway loop crash

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#561] opened 2016-06-07 19:49 UTC
This crash happened with a full server.

```
Critical: UnrealPlayerChatManager DH-La_Cambe.UnrealPlayerChatManager (Function UnrealGame.UnrealPlayerChatManager.GetIDIndex:0029) Runaway loop detected (over 10000000 iterations)
Exit: Executing UObject::StaticShutdownAfterError
Critical: FFrame::Serialize
Critical: UObject::ProcessEvent
Critical: (UnrealPlayerChatManager DH-La_Cambe.UnrealPlayerChatManager, Function UnrealGame.UnrealPlayerChatManager.AcceptVoice)
Critical: UVoiceChannel::AllowVoiceTransmission
Critical: UVoiceChannel::ReceivedBunch
Critical: UChannel::ReceivedSequencedBunch
Critical: Direct
Critical: UChannel::ReceivedRawBunch
Critical: DispatchDataToChannel
Critical: BunchData
Critical: UNetConnection::ReceivedPacket
Critical: UNetConnection::ReceivedRawPacket
Critical: UTcpNetDriver::TickDispatch
Critical: UpdatePreNet
Critical: ULevel::Tick
Critical: (NetMode=1)
Critical: TickLevel
Critical: UGameEngine::Tick
Critical: Level La Cambe
Critical: UpdateWorld
Critical: UServerCommandlet::Main
Exit: Exiting.
Log: FileManager: Reading 24 GByte 24633 MByte 25166154 KByte 190 Bytes from HD took 34.349447 seconds (33.890450 reading, 0.458998 seeking).
Log: FileManager: 27.523169 seconds spent with misc. duties
Uninitialized: Name subsystem shut down
Uninitialized: Log file closed, 06/06/16 19:01:11
```

**Comment by handsm** [comment] 2016-06-09 19:42
Theel and I looked at this after we all discussed crashes. Nothing apparent, only some extremely unlikely and obscure possibilities.

The reported runaway loop function, UnrealPlayerChatManager.GetIDIndex() looks to be almost completely harmless. The only way it appears able to cause a huge loop is if the ChatRestrictions array is somehow of enormous size. There are many functions that run a for loop to iterate through ChatRestrictions or a similar array called StoredChatRestrictions. Although this seems extremely unlikely, we can guard against it by exiting the loop in these functions if it reaches a nonsensical length.
```
simulated protected function int GetIDIndex(int PlayerID)
{
	local int i;

	if ( PlayerID < 1 )
		return -1;

	for ( i = 0; i < ChatRestrictions.Length; i++ )
		if ( ChatRestrictions[i].PlayerID == PlayerID )
			return i;

	return -1;
}
```

Looking at how and where the ChatRestrictions array gets increased, it all looks safe. There are a couple of places where the length is increased by 1, but not inside any loops. And sometimes an index int is passed into a function to update a ChatRestrictions array member, but the index is always first checked by a simple IsValid() function, which makes sure it is within the existing array range, so there's no chance of accidentally increasing the array by creating a new member with a huge index value.

The only other obscure possibility we noticed is that all BroadcastHandler actors (this is one) get chained. The first stores the next as a NextBroadcastHandler reference, and so on. As with any actor chain, this is occasionally looped through, and also each BH routinely passes on broadcast functions down the chain. So if any BH somehow manages to get an earlier BH or itself as the NextBroadcastHandler, it will create a feedback loop that I guess will cause a crash. This should never happen and is undoubtedly paranoid stuff ! But there appear to be no specific checks against it - the relevant function is BroadcastHandler.RegisterBroadcastHandler(). We can easily add those simple checks.

To do all this, we need:

- a new DHPlayerChatManager class to UnrealPlayerChatManager - full of checks on length of ChatRestrictions loops
- a new DHChatHandler class to replace UnrealChatHandler - with modified RegisterBroadcastHandler() function to prevent actor chain feedback loop
- modified DHBroadcastHandler class - to include same modified RegisterBroadcastHandler() function

I've committed these changes so you can at least see the issues we were looking at. Feel free to retain or revert, based on our paranoia level ! All checks added write a log warning, as well as preventing the runaway loop.

**Comment by handsm** [comment] 2016-06-15 14:47
I suggest closing this issue. It was very likely a one off incident, possibly linked to the general crash situation we think was caused by a corrupted v7.0.0 build. I doubt the changes I introduced have solved anything.

Would probably be worth adding a screen broadcast if any of my changes ever do prevent a runaway loop. I have a log entry in there, but it would most likely go unnoticed. A runaway loop prevention is very unlikely but a big deal if it ever does happen, so I think a screen broadcast would be proportionate.

**Comment by cmbasnett** [comment] 2016-06-17 00:07
Closing. Can re-open if we see it happening again.

**Comment by cmbasnett** [comment] 2017-10-24 10:43
This has re-surfaced, re-opening.

**Comment by cmbasnett** [comment] 2017-10-28 02:15
Just a heads up, I think the error message was misinterpreted in the past, and it's not surprising that the "safeguards" put in place didn't actually do anything.

```
Critical: UnrealPlayerChatManager DH-La_Cambe.UnrealPlayerChatManager (Function UnrealGame.UnrealPlayerChatManager.GetIDIndex:0029) Runaway loop detected (over 10000000 iterations)
```

What this means is that `GetIDIndex` was *called* over 10000000 times in a single stack frame, which indicates a run-away loop higher up in the stack, rather than a problem in the function itself.

I get the feeling that the problem lies perhaps in the way the code is using using a linked list to iterate through the registered broadcast handlers (i.e. `NextBroadcastHandler`). I can see that there were safeguards put in place to ensure that, at the very least, a broadcast handler would never register *itself* as it's own `NextBroadcastHandler`. It's possible however, that the linked list could have 3 elements, 2 of them being identical, which would result in the crash we see (eg. `A`>`B`>`A`).

What's bizarre, though, is that the crash happens seemingly when the server is at *load*, we'd expect that type of scenario I described above to happen basically right away; I don't see where a new broadcast handler is being added mid-game or how this would end up happening.

Needs more investigation, might need more eyes on it @handsm.

**Comment by AndrewTheel** [comment] 2018-03-21 08:57
This hasn't happened in awhile, going to close, but my guess is it will resurface in the future and we'll want to look more into it.

**Closed by AndrewTheel** 2018-03-21 08:57 UTC
Labels: crash
