### ISSUE TITLE
[Map Bugs - Thread is maintained] Report/Collection of Bugs/Flaws from INFANTRY Maps -- Update -- 04.09.2022

### ISSUE THREAD

**Issue by X2T5** [DarklightGames/DarkestHour#1491] opened 2022-07-30 16:43 UTC
### --=== DH-Donner_Bolts ===--

**_-- Bug Description 1 of 2 --_**

- Change "Allied Nation" from Britain to USA in the "Map Vote Screen" of this map

![0](https://user-images.githubusercontent.com/108025605/186184783-bf7bf427-a62e-4625-b206-5c94944d7b79.png)

**_-- Bug Description 2 of 2 --_**

- The weapon class slots of the allied nation "USSR" are _**duplicated**_, the difference is only in the order of the weapon listing 

![11](https://user-images.githubusercontent.com/108025605/182638871-656ca4a5-4cb0-471b-9fc1-f4efca1ca29f.png)

**Comment by shiftycats** [comment] 2022-07-31 13:36
> --=== DH-Leningrad_Push ===--
> * Game crashes when trying to load the map

Fixed in 20f29f6.

> --=== DH-Donner_Bolts ===--
> * The U.S. weapons layout is faulty

It has multiple loadouts for Allies to include all bolt rifles and nations (Axis only has one nation in the game at the moment). Donner Bolts is just a wacky little warmup map.

The grenades are an oversight though. Fixed in 7db958d.

> --=== DH-Butovo_Advance_Event ===--
> * The different category entries are missing for the "Map Vote Screen" of this map

This is a temporary event map; it's alright for them not to include voting info.

> --=== DH-Armored_Hill112_Advance ===--
> * Change "Allied Nation" from USA to Britain in the "Map Vote Screen" of this map

Fixed in c03149c.

> --=== DH-Dom-Pavlova_Advance ===--
> * In this trench at the starting point, which is difficult to see from the driver's point of view, the German team very often loses a limited and valuable "StuG III" early in the game!
> * Please place an obstacle at this point or raise the trench at this point so that no vehicle can get stuck (fall in) there

Duplicate of #1255 

----

Thank you for finding the time to report the bugs!

In the future, please consider submitting reports in separate issues (at least on per map basis), it's more convenient that way.

**Comment by X2T5** [comment] 2022-07-31 18:52
Thank you for your feedback and your work.

I do not want to open too many individual threads ... that was the idea

**Comment by X2T5** [comment] 2022-08-01 16:50
Thank you very much for your feedback and work.

I do not want to open too many individual threads to keep the forum clean... that was the idea

**Closed** 2022-09-04 10:29 UTC
Labels: bug
