### ISSUE TITLE
Machine-guns are able to easily kill anti-tank guns

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#886] opened 2017-10-24 20:18 UTC
Grab an MG42 and fire into an anti-gun, it won't take long until it's completely destroyed. Doesn't seem right!

**Comment by handsm** [comment] 2017-10-26 15:17
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/9017d55e01844af11784c7d0e34eff683aa76877.

In the past APCs and AT guns relied on a minimum APCDamageModifier threshold in the TakeDamage() function, which prevented damage by bullets. This has long since been removed, so if a DamageType isn't meant to damage APCs/AT guns, then it should simply have an APCDamageModifier of zero, which ordinary bullet DamageTypes do have.

But all bullets use a special MyVehicleDamage for hits on vehicles and all these are based on the classes DHVehicleDamageType and ROVehicleDamageType. The problem is the ROVehicleDamageType class has an APCDamageModifier of 0.025, i.e. bullets do 2.5% of normal damage when hitting a vehicle. Reduces damage to just a couple of so of health points, but blast an MG42 into an AT gun - or an APC or armoured car for that matter - and it fairly quickly racks up enough hits to destroy it.

Fix simply sets the APCDamageModifier to zero in DHVehicleDamageType.

**Closed by handsm** 2017-10-26 15:17 UTC
Labels: bug, guns, live build

**Comment by handsm** [comment] 2017-10-27 11:08
In commit https://github.com/DarklightGames/DarkestHour/commit/a8eb342d0f4b1ce3262cfc8af6128e6a25cdeef7 I deleted all the separate VehicleDamageTypes for every bullet and the associated functionality, which served no purpose.

RO added a separate a MyVehicleDamage property (in addition to the normal DamageType) in ROBullet, with the description "stupid hack we need because TakeDamage() doesn't like our ROWeaponDamage for vehicles". Perhaps that was some kind of problem in the past, although it's hard to see why, but it certainly isn't a problem or a requirement now.
