### ISSUE TITLE
Server Crash Log

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#876] opened 2017-10-22 21:21 UTC
`STEAMAUTH : Accepted Client : SteamID [1:61860990] (76561198022126718)
STEAMAUTH : Sending updated server details - [v8.0] Darklight Games Server (tinyurl.com/dh8beta) 80 | 128
STEAMAUTH : Accepted Client : SteamID [1:34452411] (76561197994718139)
Open myLevel 10/22/17 13:51:42 75.68.116.166:65177
STEAMAUTH : Accepted Client : SteamID [1:47270929] (76561198007536657)
Open myLevel 10/22/17 13:51:45 89.79.82.190:64159
Close TcpipConnection 89.79.82.190:64159 10/22/17 13:51:45
STEAMAUTH : GS Approve Couldn't find SteamID [1:211004283]
Open myLevel 10/22/17 13:51:45 89.79.82.190:64159
New Player FORGOTTENHOPE{RNL}  ID = 76561198128199883
DHPlayerChatManager DH-Putot-en-Bessin_Advance.DHPlayerChatManager (Function DH_Engine.DHPlayerChatManager.GetIDIndex:0029) Runaway loop detected (over 10000000 iterations)
Executing UObject::StaticShutdownAfterError
FFrame::Serialize
UObject::ProcessEvent
(DHPlayerChatManager DH-Putot-en-Bessin_Advance.DHPlayerChatManager, Function UnrealGame.UnrealPlayerChatManager.AcceptVoice)
UVoiceChannel::AllowVoiceTransmission
UVoiceChannel::ReceivedBunch
UChannel::ReceivedSequencedBunch
Direct
UChannel::ReceivedRawBunch
DispatchDataToChannel
BunchData
UNetConnection::ReceivedPacket
UNetConnection::ReceivedRawPacket
UTcpNetDriver::TickDispatch
UpdatePreNet
ULevel::Tick
(NetMode=1)
TickLevel
UGameEngine::Tick
Level DH-Putot-En-Bessin
UpdateWorld
UServerCommandlet::Main
DHPlayerChatManager DH-Putot-en-Bessin_Advance.DHPlayerChatManager (Function DH_Engine.DHPlayerChatManager.GetIDIndex:0029) Runaway loop detected (over 10000000 iterations)

History: FFrame::Serialize <- UObject::ProcessEvent <- (DHPlayerChatManager DH-Putot-en-Bessin_Advance.DHPlayerChatManager, Function UnrealGame.UnrealPlayerChatManager.AcceptVoice) <- UVoiceChannel::AllowVoiceTransmission <- UVoiceChannel::ReceivedBunch <- UChannel::ReceivedSequencedBunch <- Direct <- UChannel::ReceivedRawBunch <- DispatchDataToChannel <- BunchData <- UNetConnection::ReceivedPacket <- UNetConnection::ReceivedRawPacket <- UTcpNetDriver::TickDispatch <- UpdatePreNet <- ULevel::Tick <- (NetMode=1) <- TickLevel <- UGameEngine::Tick <- Level DH-Putot-En-Bessin <- UpdateWorld <- UServerCommandlet::Main

Exiting due to error
Exiting.
FileManager: Reading 0 GByte 658 MByte 371 KByte 565 Bytes from HD took 1.008993 seconds (0.859993 reading, 0.149000 seeking).
FileManager: 0.783994 seconds spent with misc. duties
Name subsystem shut down
Steam_: BugslayerUtil.DLL not found
Setting breakpad minidump AppID = 1280`

**Comment by handsm** [comment] 2017-10-23 17:29
Same as this one, I believe: https://github.com/DarklightGames/DarkestHour/issues/561

@AndrewTheel : we looked at this together after the DH v7.0 release and the several bugs that appeared. I wrote it up pretty thoroughly so I won't repeat here. We added what we thought were pretty paranoid safeguards but it must be something else. At the time we felt it was most likely the result of the corrupted file build in v7.0, which was quickly patched, and I don't think it's been seen since. The earlier bug was reported as having happened with a full server - was it full, or very busy, when this happened?

**Comment by AndrewTheel** [comment] 2017-10-23 17:54
We had 84 players on the server, so yea it was populated.

**Comment by AndrewTheel** [comment] 2017-10-23 18:22
Here is what I think is happening:

Lots of players are on the server, lets say 80. Someone talks on the mic, it runs a function `AcceptVoice` on each other player on the server, which then runs the ChatRestriction loop. Even though its not actually doing 1000000 iterations, the script thinks it will and therefore calls it a runaway loop and "crashes".  I'm pretty sure this 1,000,000 iterations thing is not actually "doing" that many but predicting that many.  However, lets say 16 of the 80 players talk at nearly the same time. That is 16x80x80 iterations, which is getting up there 1/10th.  So perhaps something else is going on, but here is what I think we should do...

From my understanding, if `ChatRestrictions` are the "muting" of other players, etc. It does not work anyways because it uses the mask system (which has been deprecated), so we should remove all its iteration loops, any checks of it, and really just any use of it. Because it will never work anyways.

The `AcceptVoice` function should be changed to: `{ return true; }` And basically any thing else that uses or loops ChatRestrictions should be deprecated out.

**Comment by cmbasnett** [comment] 2017-10-24 10:43
Duplicate of #561, closing this one and re-opening the other one.

**Closed by cmbasnett** 2017-10-24 10:43 UTC
Labels: bug, crash
