### ISSUE TITLE
The blur remains for grenades close enough to cause screen blur

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#670] opened 2017-02-26 18:15 UTC
The screen blur that happens when a grenade goes off nearby remains forever until the player shoots his weapon.  This bug is pretty new as Basnett and I think it was not in 7.1

**Comment by dynamittt** [comment] 2017-02-27 00:56
I can confirm this, noticed it today while playing on GG. I have seen this in RO long time ago, was caused by a custom vehicle.
Here is a snippet from the default properties of the projectile that caused this:

```
simulated function DoShakeEffect()
{
    local PlayerController PC;
    local float dist, Scale;

    // End:0x1B9
    if(Level.NetMode != NM_DedicatedServer)
    {
        PC = Level.GetLocalPlayerController();
        // End:0x1B9
        if((PC != none) && PC.ViewTarget != none)
        {
            dist = VSize(Location - PC.ViewTarget.Location);
            // End:0x1B9
            if(dist < (DamageRadius * 3.0))
            {
                Scale = ((DamageRadius * 3.0) - dist) / (DamageRadius * 3.0);
                Scale *= BlurEffectScalar;
                PC.ShakeView(ShakeRotMag * Scale, ShakeRotRate, ShakeRotTime, ShakeOffsetMag * Scale, ShakeOffsetRate, ShakeOffsetTime);
                // End:0x18D
                if((PC.Pawn != none) && ROPawn(PC.Pawn) != none)
                {
                    Scale = Scale - ((Scale * 0.350) - ((Scale * 0.350) * ROPawn(PC.Pawn).GetExposureTo(Location + (float(50) * -Normal(PhysicsVolume.Gravity)))));
                }
                ROPlayer(PC).AddBlur(BlurTime * Scale, FMin(1.0, Scale));
            }
        }
    }
    //return;    
}
```

```
{
    ShakeRotMag=(X=0.0,Y=0.0,Z=200.0)
    ShakeRotRate=(X=0.0,Y=0.0,Z=2500.0)
    ShakeRotTime=3.0
    ShakeOffsetMag=(X=0.0,Y=0.0,Z=10.0)
    ShakeOffsetRate=(X=0.0,Y=0.0,Z=200.0)
    ShakeOffsetTime=5.0
    BlurTime=6.0
    BlurEffectScalar=3.0
  }
```

**Comment by cmbasnett** [comment] 2017-02-27 21:39
I tried fruitlessly to get this to happen in single-player on Target Range, but I notice it virtually non-stop in the live game. I notice that there was a refactor regarding inheritance and functionality in the `DHThrowableExplosiveProjectile` class that the grenades inherit from (55e68ce3).

The `DoShakeEffect` is copied, but heavily modified; allegedly it does the same thing, but I can see how there might be subtle differences that could result in odd behavior (eg. the `BlurTime` ending up at some huge value). That would be the best place to start looking, in my opinion.

We should sort this out as fast as possible, as it's very distracting.

**Comment by handsm** [comment] 2017-02-28 12:26
Figured it out. Offending line is `Scale -= (0.5 * (1.0 - BlastExposure));`

My calculation is incorrect and can result in a negative value for Scale, resulting is passing a negative time into the AddBlur() function. If that happens, a blur effect is added but the mechanism to clear it after a set time is not triggered, so it stays on the screen until something else adds a working blur effect.

Occurred when Scale would normally be low, so could be recreated by an explosion towards the maximum blur distance and/or shielded.

The offending calculation is intended to scale down the blur effect if the player is not fully exposed to the blast. BlastExposure is 0 to 1 and blast shielding factor is 1 minus exposure. It's meant to reduce the Scale by 50% of the blast shielding factor, i.e. even if fully shielded the player should still get 50% blur scaling.

I've mistakenly subtracted the 50% shielding as a literal, when it should applied as a reduction factor. For example, if the in Scale is 0.3 and the player is only 20% exposed, the shielding reduction factor should be 0.4 or 40% (half of 80% blast shielding), so the final Scale result should be 0.18. I have rather dumbly subtracted 0.4, which gives a result of -0.1 and .......

**Comment by handsm** [comment] 2017-02-28 12:55
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/afd0bcfcb1cfbef282d2b701603ea4eab80a1952.

Fixed the incorrect line and now expressed the reduction factor as BlastShielding instead of BlastExposure, which is intuitive and makes it a little more readable.

Same fix in the arty shell class (other projectile classes are not affected).

**Closed by handsm** 2017-02-28 12:55 UTC
Labels: bug, live build

**Comment by cmbasnett** [comment] 2017-02-28 18:42
I will port this fix over to the `live` branch and release as `v7.2.2`.
