### ISSUE TITLE
Grenades are often not exploding

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#562] opened 2016-06-07 19:51 UTC
Grenades are often not exploding and this is just a visual problem.  The grenade just seems to delete on the ground, and bodies go flying with no effect.  I've witnessed this first hand on Vierville, however others were reporting it across the board.

**Comment by AndrewTheel** [comment] 2016-06-07 20:32
This may be affecting rockets as well, so make sure to look into that.  Also TMK this is only achievable in a live situation, making it hard to debug.

**Comment by handsm** [comment] 2016-06-08 15:22
Confirmed this is caused by the server destroying the grenade projectile and sending that Destroy() instruction over the network to the client BEFORE the client has time to call its own Explode() function.

Caused by alterations to accommodate special net-culling BSP. There is more than one way to resolve/revert this, but it's a relatively easy fix. I want to do it carefully and may not have time to do that today, so assume it will be done early tomorrow.

**Comment by handsm** [comment] 2016-06-09 22:22
Fixed in commit mentioned above.

In general, this has highlighted that any projectile that is fully replicated (i.e. not just torn off) has to safeguard against the server destroying the actor before the client has time to play impact/explosion effects. I can think of 4 ways to do that - and different projectiles use some of those methods, some do not. I would rank this in order of preference, from worst to best:

4. Play impact/explosion effects in Destroyed(), so they are guaranteed to play (grenades used to have this, but I removed to make the special BSP work).
3. Delay server destruction by arbitrary time delay (cannon shells do this).
2. Tear off the actor when it is time to destroy it on the server, then let the client decide when to destroy its local torn off actor (smoke projectiles do this, something I've added previously).
1. Make the projectile a bNetTemporary actor, which means it gets torn off as soon as it gets replicated to the client & so cannot receive a Destroy instruction from the server (bullets do this, though for the purpose of network efficiency).

I don't think mortar shells or arty shells have any of these safeguards.

Method 4 is worst because it's crude and allows no control over where you may want to avoid explosion/impact effects. But it's the ultra safe method, so it's used in this fix. We can improve later.

Method 1 is best (for the future) because it is a significant net optimisation - it isn't always possible though. It probably isn't possible for mortar shells and method 2 would be my goal there. In ballistics terms, I'd think method 4 is suitable for grenades (very short flight path, slight loss of rotation precision not a big deal). But we'd need to make sure the adjustments to fuze time get replicated to the client with the initial batch of variables, as nothing will reach the client after it's torn off. And I'm pretty certain method 4 will be suitable for arty shells.

**Closed by handsm** 2016-06-09 22:22 UTC
Labels: bug
