### ISSUE TITLE
Voice commands sometimes do not work

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#516] opened 2016-01-06 10:44 UTC
We've gotten strange reports from various players that the voice command menus do not show up for certain players. I was skeptical of this claim, convinced it was just an issue of their input keys not being bound correctly. However, I encountered this first hand playing on the trunk server.

This is how it went:

1. Joined trunk server.
1. Voice menu wouldn't display when hitting the correct button
2. Couldn't see or hear other players' voice commands
3. Checked settings, verified that "All" voice commands were enabled.
4. Changed setting to something (can't remember what, possibly "Except insults"
5. Voice command menu now shows up!
6. Selecting a voice command displays the following message whenever a voice command is done: *TEAM* [DH]Basnett:` (notice no message)
7. Still can't hear any voice commands.
8. Reset connection to server.
9. Everything works fine!

Very bizarre. Possibly has something to do with the changes that were made nearly a year ago to the way settings are saved and loaded in the interface.

**Comment by handsm** [comment] 2016-01-06 19:04
Possibly unrelated, but in case this offers any clue to a potential problem in the way settings are saved: I noticed my config would occasionally 'lose' the show HUD options (more specifically, the 'hide HUD' option would become checked) on starting the game sometimes. I would uncheck that box, then some time later I would notice the HUD had disappeared again and I would need to repeat. From memory, I think one of the other HUD options was also lost from config; probably the compass.

**Comment by AndrewTheel** [comment] 2016-07-05 19:49
I've been unable to use a voice command, then die, and then be able to.  I don't think this is a settings save issues, I think it might be something to do with the spawning system.  Similar to the way certain players are not assigned skins correctly.

**Comment by handsm** [comment] 2016-10-10 14:25
I think I've found the cause of this bug & have a simple fix. Should be committing soon.

**Comment by handsm** [comment] 2016-10-12 17:24
Should be fixed in commit https://github.com/DarklightGames/DarkestHour/commit/5872d65b425df3f78440feb3e014a207bca85569.

**Comment by handsm** [comment] 2016-10-28 11:29
Closed as believed fixed. We can re-open if testing shows otherwise.

**Closed by handsm** 2016-10-28 11:29 UTC
Labels: bug, gameplay
