### ISSUE TITLE
Cannot respawn. Continue button greyed out for no apparent reason.

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#592] opened 2016-08-14 01:02 UTC
Playing as tanker. Its time to respawn. Select Vehicle&SP and click Continue. Vehicle seems to be reserved. Suddenly,  vehicle's name is "greyed out" and title says <Reserved>. Continue button is greyed out. Will not spawn with the vehicle and at the SP I have selected.
Tried switching to infantry result is the same. Cannot click on Continue button even though teams are balanced and spawn point is selected. Switching roles and Teams does not help either.
If you try to press ESC to close the RoleSelectMenu, it will reopen immediately on its own.
Happens randomly, no idea why.

**Comment by cmbasnett** [comment] 2016-08-14 22:57
I think I know the cause of this one. When the vehicle you currently have selected is "taken away" because of someone reserving it, the selected index on the vehicle screen is set to `-1`, instead of the normal `0` (None), which makes selecting the continue button impossible. This was done as a way to stop tankers from accidentally spawning without a tank when someone reserved the vehicle they had selected.

I'm open to ideas on how to make this work in a way that isn't disruptive to players and doesn't require extra clicking about.

**Comment by dynamittt** [comment] 2016-08-15 21:29
Colin hi, the thing is, I am not really aware of how the new DH interface works code wise.
Lets assume for a second its not me but a random player:
DHPlayer does not care if his vehicle was taken away (reserved by someone else), or there was some bug that prevents him from spawning with his vehicle of choice.
The end result is what we are interested in, and it ultimately leads to DHPlayer not being able to spawn at all (as described above).
"When the vehicle you currently have selected is "taken away" because of someone reserving it..."
For some reason I do not believe that the vehicle was really taken by someone else:
how could a vehicle that I have reserved 15 seconds ago suddenly becomes reserved by someone else?
Why did selecting an "infantry" spawn point as tanker and attempting to spawn on foot did not allow me to click the continue button?
Why did changing role to infantry and attempting to spawn on foot on any spawn point did not allow me to click the continue button?
If the Vehicle was **really** taken away, why was I allowed to click the "Continue" button in the first place?
**My actual suggestion is:**
When a player selects a Vehicle, run a check to see if this vehicle has been Reserved.
When a player who has already selected a Vehicle attempts to click the _Continue_ button,
do a similar check, and if the vehicle has already been reserved, do nothing. Just update the vehicle list. Player can now select an available vehicle from the list **OR** choose to spawn on foot at any spawn point.

"This was done as a way to stop tankers from accidentally spawning without a tank when someone reserved the vehicle they had selected."

I see your point, but what If I want to spawn on foot at the rear (vehicle) spawn point and would like to join the guy who spawned with the tank before me?

And what do you think of making it possible for people to spawn together in a vehicle? Example:
Player 1 reserves a vehicle, and is prompted if he would like to allow others to spawn with him inside his tank. If he agrees, and other people select the same vehicle, they will all spawn together.
This is basically how RO2 Vehicle spawning works.
Right now, if someone spawns with a tank, and I want to join him, I could either spawn at the rear spawn point and hope I can chase him and jump inside his tank, or I could spawn at one of the "forward" infantry SPs, and hope that tank drives close enough so I can jump in.

Please note that the Vanilla Ostfront vehicle system (although heavy on channels with all those vehicles just sitting there in spawn and doing nothing), forced the guy who first took a vehicle to wait some seconds, so that people can join him without having to chase the tank like crazy.
This system also has some sort of check, that disables "waiting for other crewmembers" if all spawned players from the current wave have already jumped inside a vehicle.

As for players who want to tank alone, their only chance is to either kill the ones trying to get inside their tank, or drive away so that no one can board their tank.
So my other suggestion (although not exactly related to the current issue) is:
Either force player to wait for others/make it possible for multiple crewmembers to spawn together in a vehicle **OR** give him the ability to "lock" the vehicle. (Of course passengers should always be able to climb and ride).

**Comment by cmbasnett** [comment] 2016-08-17 21:21
We are working on sorting out the original issue posted (not able to spawn, "continue" button greyhed out). Targeting the fix to be out in the 7.0.3 patch.

**Comment by cmbasnett** [comment] 2016-08-18 03:39
Fixed in commit 60b50e75.

**Closed by cmbasnett** 2016-08-18 03:39 UTC
Labels: bug, deployment
