### ISSUE TITLE
Rejoining a server where you previously had weapons locked puts game in bizarre state

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#663] opened 2017-02-21 07:00 UTC
1. Get weapons locked for ~30 seconds by spawn killing.
2. Disconnect from the server.
3. Rejoin the server and observe the chaos.

**Comment by AndrewTheel** [comment] 2017-02-21 07:41
My guess or what this sounds like is that the server does everything right, but for some reason the variable isn't replicated to the client.  It should be so I'm a bit confused, but I'll look into it and try to fix it.

**Comment by handsm** [comment] 2017-02-21 10:18
Done some debugging and logged it through the process. The problem is caused because when the re-joining net client receives the instruction to set its local weapons unlock time, it doesn't yet have the GameReplicationInfo actor and so doesn't know the ElapsedTime. Results in the client having an unlock time in the past, which means weapons aren't treated as locked on the client, while they are on the server. When the server prevents a weapon firing, it makes the client display a screen message, but the client comes up with negative seconds remaining because it doesn't have the correct unlock time.

I'm looking at the best re-jig so it works in this situation.

**Comment by handsm** [comment] 2017-02-21 11:39
Got a fix - committing very soon, after stripping debug logging.

**Comment by handsm** [comment] 2017-02-21 12:06
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/f884b2d4097d9df7db304a3c1ed6244c329b7f99.

Added a slightly hacky fix using PostNetReceive()) to set the weapon lock on the client as soon as it receives the GRI. Uses a PendingWeaponLockSeconds variable, which gets recorded by the client if the LockWeapons() function fails due to not having GRI yet. If that happens, as soon as the GRI is received (a split second later), PostNetReceive() uses PendingWeaponLockSeconds to call LockWeapons() again, this time working properly.

There would be other ways of doing this, but although I said it was a little hacky, this method works with the existing system and doesn't require any redesign or refactor, so it's very suitable just before the 7.2 release. It's also actually a pretty clean solution.

**Closed by handsm** 2017-02-21 12:06 UTC
Labels: bug
