### ISSUE TITLE
Sherman, Stuart & jagdpanzer IV hull MG fire off-center in multiplayer

### ISSUE THREAD

**Issue by Elewyn** [DarklightGames/DarkestHour#535] opened 2016-02-15 10:13 UTC
When using the hull mg in Shermans, the tracer rounds are firing off to the forward right/left of the gun barrel. It seems to be a pretty big gap between where the bullets are comming from and the gun barrels position (sort of diagonal fire), making accurate fire extremely difficult.

**Comment by handsm** [comment] 2016-02-27 18:53
I'm not sure I see much of an issue myself, but I think these things can be very subjective and personal. I reckon my eyes just follow the tracers, rather than where the gun seems to be pointing.

But I've looked at the MG model and it isn't quite centred and it isn't symmetrical. So I've adjusted the model and re-rigged it with everything centred. I've also changed the camera position slightly and brought the forward offset of the bullet launch position and the muzzle flash slightly closer, which seems to give a good view down the barrel.

Having made that change I can see that the old barrel looked a bit wonky - almost curved at the end. I wonder if it was that that was causing the issue.

Changes committed in SVN update 1121 (mesh) and commit https://github.com/DarklightGames/DarkestHour/commit/283d3bbc1e02c691ec05cbbf8ab58565545555ef.

**Comment by Elewyn** [comment] 2016-04-17 01:52
Honestly I think it might just be a server issue, managed to get a screenshot of the problem this time: http://i.imgur.com/91qHRTT.jpg (Jagdpanzer IV/70)

**Comment by handsm** [comment] 2016-07-16 17:28
Hmmm .... I believe this is caused by the fact that objects are not in exactly the same place or rotation on a network client (your own computer) as they are on the server. Basically, the bullet is starting from a position that is perfectly lined up with the hull MG on the server, but which is a bit off on your own computer - because your tank/MG is in a slightly different position to where it is on the server. Sounds weird, I now, but ... 

The server holds the only definitive version of the game world/state and all the various objects in it. But we never see that. Our own computers are just running a simulation of it. Mostly our simulation is pretty accurate, even though we are only ever simulating part of the overall game world (the server decides what it thinks we need to have, and cuts away huge swathes of the world, to make the network run tolerably).

In your local simulation, you have a pretty accurate location/rotation of everything the server thinks is important. But never quite the same location/rotation. The server expects and tolerates modest differences, which get corrected if they get out of hand, or otherwise gradually as things move around. And some precision of location and rotation get lost when that information is passed ('replicated') to you from the server. These differences can be confirmed by logging the location/rotation of objects on both the server and a net client.

So, in this case the server is spawning bullets, including tracer bullets, at exactly the correct location and firing direction - correct for the server. It knows that you need to have those bullets in your local simulation, so it replicates them to you as soon as it can. This means that your machine is told to 'spawn' the particular bullet actor at such-and-such location and rotation. In fact, there is a slight, variable delay before replication happens, so the bullet will have travelled a bit before you get it, meaning it starts a little way along its path on your machine (the bigger your ping/lag, the further it will generally fly before you get it).

With normal bullets you never know about any this, but with a tracer you see the results. What I believe you are seeing is your local copy of the bullet starting in a position that would be - and is - perfect on the server, but not quite right compared to the position of the tank/MG on your computer. So you see a tracer a bit off to the side. Doesn't significantly effect where the bullet goes. And normally you wouldn't notice the 'off' start position, but with a very focussed view down an MG barrel and a bright tracer, it tends to stand out.

Sadly, I don't think this is fixable, at least not without some radical re-working/re-thinking of the server/client interaction when firing, which would probably cause more problems than it would solve.

This is really an issue for Shermans, Stuart (same MG & set up) & the jagdpanzer IV. It's there in vehicles, but you don't notice it on other German hull MGs, as they are in a 'kugelblende' mount, which includes the optical sight fixed off to one side of an MG34. So you naturally see the tracer fire from off to the side, which with magnification is quite pronounced.

As far as I know, American hull MGs were much simpler mounts, without optics. I believe the bow gunner aimed by observing the fall of the bullet impacts and/or tracers, either through an overhead periscope or from having his head out of an open hatch. And the JP4, as far as I know, just had an MG42 held in sling from the roof, with the m-gunner looking through a crude hole in the front armour plate. So he would be sighting the MG more like an infantryman, although I imagine with a tunnel view. Because of this, the US or JP4 m-gunner is sighting down the line of the barrel, not looking from off to one side, so any deviation is apparent.

In game, these MGs are shown as if they had plain, unmagnified sights, where in reality I don't believe they had any. That raises a question of realistic depiction, although that's another issue for another day ! I suppose the circular view on the JP4 could just about represent the view through the sight hole. But I think the bow 30 cals on Shermans and Stuarts are an artificial view. Those tanks don't have opening hatches for the bow gunner, and likely never will, but I do wonder if we could have the bow gunner's view though an overhead periscope .....

**Comment by handsm** [comment] 2016-10-29 15:14
Closed as I don't think this can be improved.

**Closed by handsm** 2016-10-29 15:14 UTC
Labels: vehicles, wontfix
