### ISSUE TITLE
Field of view is incorrect after swapping the barrels on the machine-guns

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#702] opened 2017-05-15 08:45 UTC
Real easy to reproduce. Just swap the barrel on any machine-gun and check out the field of view.

**Comment by AndrewTheel** [comment] 2017-05-15 16:39
Duplicate of:
https://github.com/DarklightGames/DarkestHour/issues/679

**Closed by AndrewTheel** 2017-05-15 16:39 UTC
Labels: infantry weapons
