### ISSUE TITLE
Vehicle passengers do not get minefield warnings for vehicles in a minefield

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#465] opened 2015-11-19 04:04 UTC
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

----------------------------------------

I believe this is a RO bug and perhaps a bug with the minefield itself (and not vehicles).  We can move this to `on hold` as it's not that important.

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/466

**Comment by handsm** [comment] 2015-12-23 08:08
Oh, it ended up as a complete & utter re-design, no mistake. What started out as an attempted simple fix, ended up as finding fundamental flaw after flaw with the original mine volume. I haven't looked at the code in well over a year, so when the 6.0 dust has settled I'll review & update to 6.0 and share with you. It was well commented to explain, so shouldn't be difficult for either of us to pick up.

**Comment by handsm** [comment] 2016-08-21 14:53
Fixed as part of fundamental redesign of ROMineVolume in commit https://github.com/DarklightGames/DarkestHour/commit/4a0bee1d1f862c1896097a3ac53919ae92f8bc38.

The problem is because only the vehicle triggers the MV's Touch() event, because player pawns (DHPawns) in a vehicle have the collision switched off. So the MV only becomes aware of the vehicle pawn. The driver gets warnings because he is controlling the vehicle pawn, so he receives warning messages sent to it. But the passengers are controlling separate VehicleWeaponPawns, which don't have collision and never Touch() the MV, so never receive any warnings.

Solution summary: when a vehicle enters a MV or we find a vehicle in a MV, we now loop through all occupants & give a warning to any players.

**Comment by handsm** [comment] 2016-10-29 15:15
Closing as believed fixed. New minefields functionality in general should be a specific focus of testing prior to 7.1 release.

**Closed by handsm** 2016-10-29 15:15 UTC
Labels: bug, vehicles
