### ISSUE TITLE
Vehicles sometimes fly into the air when destroyed

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#455] opened 2015-11-09 08:53 UTC
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

---

Tanks are suddenly flying 1-5 meters into the air when destroyed.  Noticed this on Freyneux and Raids. 

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/456

**Comment by handsm** [comment] 2016-01-10 18:46
Can anyone provide any repro steps? If not I'll close this and we can re-open if it's ever seen again.

**Comment by AndrewTheel** [comment] 2016-01-11 05:50
I'm 100% sure it is bodies spawning after being "killed" in or even around the tank.  We need to make it so bodies and weapons don't drop when someone inside is killed.

**Comment by handsm** [comment] 2016-10-29 15:09
Closing as I've never seen this and we can't reproduce it. Let's re-open if the problem is ever seen again.

**Comment by AndrewTheel** [comment] 2016-10-29 15:46
It is when there are multiple people in the tank and the tank is destroyed, the ragdolls collide with the tank and it CAN get glitchy and send the tank into the air.  I saw a Sherman go flying 10 feet high and see this very often.

**Comment by handsm** [comment] 2016-11-17 16:02
Should be fixed in commit https://github.com/DarklightGames/DarkestHour/commit/09f75ea37b5c423432e09be82c1e2ceda5f93297.

Will write this up properly tomorrow as have to go out now.

**Comment by handsm** [comment] 2017-01-08 17:34
Bump as reminder for me to write this up, then close it!

**Closed** 2017-01-22 10:18 UTC
Labels: bug, vehicles
