### ISSUE TITLE
Scoped Enfield No. 4 cross-hair is misaligned

### ISSUE THREAD

**Issue by kuopassa** [DarklightGames/DarkestHour#526] opened 2016-02-01 17:07 UTC
After just playing a round of good old Maupertus with Scoped Enfield No. 4, I noticed several times that the impact "puff" seems to be a bit off to the left. Maybe...

**Comment by cmbasnett** [comment] 2016-02-03 21:09
Just checked this out and it seems you may be right. The splash seems to be consistently off to the left by just the slightest amount. Will look into fixing this for 6.0.4.

**Comment by cmbasnett** [comment] 2016-02-03 21:16
Confirmed that the texture is off by about a pixel and a half.

![screenshot 2016-02-03 13 15 37](https://cloud.githubusercontent.com/assets/5035660/12797330/44f2ff4e-ca78-11e5-8242-5adb45df96c2.png)

**Comment by AndrewTheel** [comment] 2016-02-03 22:37
The problem is it is only off 1 pixel in 1024x1024, because you can't have a "center" in an even number of pixels.  The larger your resolution the more you'll notice it being off.  TMK the only fix is to adjust the value as I had done, but that value harms people with 4:3 aspect, so I haven't a clue if this is actually fixable or not.

**Comment by kuopassa** [comment] 2016-02-04 07:49
Could the cross-hair be a bit thicker then? :-)

**Comment by AndrewTheel** [comment] 2016-05-19 18:43
Fixed in commit: e95b6b0

https://github.com/DarklightGames/DarkestHour/commit/e95b6b02afcccfb1c705b820235f36d1c711de84

**Closed by AndrewTheel** 2016-05-19 18:43 UTC
Labels: bug, infantry weapons
