### ISSUE TITLE
Tank commander and/or turret hatch are sometimes not shown in correct position to other players 

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#533] opened 2016-02-13 19:04 UTC
**Tank turret and hatch bugs:**

Bug #1: Was running around as infantry. Suddenly noticed an enemy tank around the corner of a building: Tank's turret was pointing in a strange direction. After a split-second, tank's turret got "updated" to proper rotation.

Bug #2: Saw an enemy tank approaching: tank commander's hatch was open but there was nobody inside this position: the attempted  "whack-a-mole" shot yielded no result. After couple of seconds, driver switched to tank commander's position (I could see this using my binoculars) and commander's hatch no longer appeared to be open! Another thing I noticed: sometimes shooting at an open hatch will result in a blood-puff emitter being shown and a kill scored on the commander, no matter if no head was visible!

**Comment by cmbasnett** [comment] 2016-02-28 23:54
First part of your issue is not fixable, it's a lag issue and is buried deep in native code. The second part is legit. Assigning to @handsm .

**Comment by handsm** [comment] 2016-06-13 16:41
Closed as effectively a duplicate of https://github.com/DarklightGames/DarkestHour/issues/498.

**Closed by handsm** 2016-06-13 16:41 UTC
Labels: bug, duplicate, vehicles
