### ISSUE TITLE
Some obstacles disappear when looking in specific directions/angles

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#722] opened 2017-07-05 22:28 UTC
Many new obstacles seemingly disappear randomly when nearby and looking in different angles.

Is there a way to make it so this doesn't happen on each new obstacle?

**Comment by cmbasnett** [comment] 2017-08-21 10:41
Duplicate of https://github.com/DarklightGames/DarkestHour/issues/775

**Closed by cmbasnett** 2017-08-21 10:41 UTC
Labels: bug, task
