### ISSUE TITLE
Grenade projectiles transfer impact momentum to rag dolls

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#601] opened 2016-08-22 13:43 UTC
The new grenades can transfer momentum and move around dead corpses. Please investigate.

EDIT (Matt) : only happens on a net client, not in single player.

**Comment by dynamittt** [comment] 2016-08-22 17:13
Hello, please try the following: in a game, wait for someone to die, then throw a grenade into/on top of the corpse. The grenade **projectile** will transfer momentum to the corpse and move it.
Again, I am talking about grenade as a projectile. Grenades should not be able to move around dead bodies when they hit them. Of course the explosion will move around dead bodies which is fine. But the issue is regarding a object that weights around 600 gramm being able to move another body with weight 70 kg or more - it looks very weird in game.

**Comment by cmbasnett** [comment] 2016-08-24 17:34
This is super low priority, but we'll leave this here. Sorry for closing earlier, I misunderstood the initial report.

**Comment by dynamittt** [comment] 2016-08-24 18:51
Hehe, good to hear!
Have to admit, I got a bit frustrated when you just closed the issue without any comment.
Of course its a low priority, may be the fix is easy too, meanwhile I found some other bugs while playing on Targnon yesterday, (even got screenshots) but can't upload them right now...

**Comment by AndrewTheel** [comment] 2016-09-08 01:44
@dynamittt Do you have any clue where this is happening in the script?  Because if you can find it and the fix is extremely simple, we'll put it in and test it.

**Comment by DerekHopkins** [comment] 2016-09-23 13:45
It should be this in DHPawn:
```

state Dying
{
    simulated function TakeDamage(int Damage, Pawn InstigatedBy, vector HitLocation, vector Momentum, class<DamageType> DamageType, optional int HitIndex)
    {
        local vector SelfToHit, SelfToInstigator, CrossPlaneNormal, HitNormal, ShotDir, PushLinVel, PushAngVel;
        local float  W, YawDir, HitBoneDist;
        local int    MaxCorpseYawRate;
        local name   HitBone;

        if (DamageType == none)
        {
            return;
        }

        if (Physics == PHYS_KarmaRagdoll)
        {
            // Can't shoot corpses during de-res
            if (bDeRes)
            {
                return;
            }

            // Throw the body if its a rocket explosion or shock combo
            if (DamageType.Name == 'ROSMineDamType' || DamageType.Name == 'DH_StielGranateDamType' || DamageType.Name == 'ROMineDamType' || DamageType.Name == 'DH_M1GrenadeDamType')
            {
                ShotDir = Normal(Momentum);
                PushLinVel = (RagDeathVel * ShotDir) +  vect(0.0, 0.0, 250.0);
                PushAngVel = Normal(ShotDir cross vect(0.0, 0.0, 1.0)) * -18000.0;
                KSetSkelVel(PushLinVel, PushAngVel);
            }
.........
```

**Comment by DerekHopkins** [comment] 2016-09-23 15:37
In Class 'DHThrowableExplosiveProjectile':

```
// Matt: modified to call HitWall for all hit actors, so grenades etc bounce off things like turrets or other players
simulated function ProcessTouch(Actor Other, vector HitLocation)
{
    local vector TempHitLocation, HitNormal;

    if (Other == Instigator || Other.Base == Instigator || ROBulletWhipAttachment(Other) != none)
    {
        return;
    }

    Trace(TempHitLocation, HitNormal, HitLocation + Normal(Velocity) * 50.0, HitLocation - Normal(Velocity) * 50.0, true); // get a reliable HitNormal for a deflection
    HitWall(HitNormal, Other);
}
```
Maybe do a check like:

```
if ( (DHPawn(Other) != None && Other.Physics == PHYS_KarmaRagdoll )
{ return; }
```

**Comment by handsm** [comment] 2016-10-29 14:43
This isn't a new bug. You can remove all the added DH grenade functionality and the bug is still there. I've traced it and it's caused by a combination of factors. I'm pretty certain the bug would be there in DH 5.1, but I don't have an old version and so can't confirm. It would be there in RO except for the pure coincidence that in the relevant functionality RO stated the wrong literals for grenade damage types. So a typo error masked a bug!

The first odd thing about this bug is it only appears on a net client. In multi-player you expect problems to cause things to fail to happen on a client, not that extra effects happen. It can confuse this issue because it would be logical to test this bug in single player. I did just that and spent some time trying to recreate the problem, wondering what dynamittt was on about! :) It doesn't happen in either SP or on a listen server. So some unwanted functionality is being called specifically on clients.

Having debugged it, the root of the problem here is an obscure function called ClientSideTouch(CST) in the base Projectile class. I'm glad I found out about this. It isn't overridden anyway and every projectile inherits its basic and generally unwanted functionality:

    simulated function ClientSideTouch(Actor Other, Vector HitLocation)
    {
        Other.TakeDamage(Damage, Instigator, Location, MomentumTransfer * Normal(Velocity), MyDamageType);
    }

Calling a damage function on a client is very unusual so we need to look at where it is being called from and figure out why. CST is only called from the Touch() event, which is called natively whenever a projectile collides with certain collidable actors. Touch() does some fairly basic stuff and then calls ProcessTouch(PT) on the hit actor. PT is where the real business gets done. Actors that are world geometry or have karma, i.e. vehicle hulls, get the native event HitWall() instead of PT. HitWall() and PT are sort of paired and contain projectile-specific functionality that can be quite complex.

Note that Touch() was previously not overridden, although since DH 6.0 I have overridden it in all projectile classes, purely to add handling of collision static mesh actors. But apart from that Touch() is unaltered. This is where it calls CST, right at the end:

    if (Role < ROLE_Authority && Other.Role == ROLE_Authority && Pawn(Other) != none)
        ClientSideTouch(Other, HitLocation);

So what's going on there? It calls CST if we're on a net client and we've hit a Pawn that has an authority role on the client. Most actors on a client will have a proxy role. They will only be authority if (1) they have been spawned locally and independently on the client (generally just visual or sound effects) or (2) they were replicated actors but have been torn off by the server and now exist independently on the client with their role now switched to authority. And how could this apply to a pawn? Only for a player pawn (i.e. a DHPawn) that has been killed and is now a ragdoll body. It gets torn off in PlayDying() on the server..

Although CST isn't explained, we can figure out why the functionality is there. It is purely so projectiles can, if desired, have an effect on ragdolls on clients. Calling TakeDamage() or a similar function on the hit actor is generally the way to make things happen to it. But calls to damage functions are nearly always skipped on a client. So calling CST is a way of allowing projectiles to affect dead bodies in multi-player, although it doesn't make that very clear.

The big problem is this is very basic, generic functionality and not made specific for any projectile classes. It just calls TakeDamage() on the ragdoll, passing some very generic, assumed arguments. Totally unwanted in the case of a grenade because they don't otherwise cause any impact damage or effects. And made worse because explosion related momentum and DamageTypes end up being used.

All Projectiles have a MomentumTransfer float, which is the "momentum magnitude imparted by impacting projectile". Intended for real projectiles like bullets. Exploding projectiles, including grenades, end up using large MomentumTransfer values, but representing their explosive energy, not the originally intended impact energy. Also, while more sophisticated explosives like shells have separate DamageTypes for impact and exploding damage, grenades only have one damage type that is set up for their exploding damage. We can end up with momentum and damage properties that are intended for explosions being used for impacts. If it's a shell that won't really cause a problem because it has very high impact energy anyway, plus any unwanted effects are hidden by the big explosion. But for a grenade, with negligible impact energy, we can get unwanted effects like this.

We could think about neutralising momentum/damage properties for non-explosion functionality, even having separate variables like a shell. But the basic problem here is that calling any kind of impact functionality is entirely unwanted for a grenade. So the simple and next fix here is to remove CST altogether in the grenade class.

Really I think CST needs to go in all the projectile classes, but for now this is the only one where I can see it causing a problem. Where impact effects are wanted on ragdolls, they should be handled in the far more projectile specific and sophisticated impact functionality in PT/HitWall(). I'm specifically referring to impact effects as opposed to explosion effects on ragdolls, which are handled in completely separate explosion functionality. An example of where impact effects would be desirable imo are bullets making bodies jerk slightly, which would be very realistic. Although such functionality exists in DHPawn (as we see with grenades, however unwanted), for a variety of reasons it doesn't actually happen with bullets, where we would want it to. But that's a separate and minor issue.

Oh, how does it go wrong specifically for grenades? In the TakeDamage() function in DHPawn's state 'Dying'. It contains this functionality, which from the comment clearly originates in UT2004 but has had the DamageTypes updated:

    // Throw the body if its a rocket explosion or shock combo
    if (DamageType.Name == 'ROSMineDamType' || DamageType.Name == 'DH_StielGranateDamType' || DamageType.Name == 'DH_F1GrenadeDamType'
        || DamageType.Name == 'ROMineDamType' || DamageType.Name == 'DH_M1GrenadeDamType')
    {
        ShotDir = Normal(Momentum);
        PushLinVel = (RagDeathVel * ShotDir) +  vect(0.0, 0.0, 250.0);
        PushAngVel = Normal(ShotDir cross vect(0.0, 0.0, 1.0)) * -18000.0;
        KSetSkelVel(PushLinVel, PushAngVel);
    }

It uses the passed Momentum (unfortunately grenade explosion momentum) to calculate PushLinVel and PushAngVel and then calls the native function KSetSkelVel() on the dead pawn, making it move. Note the nasty use of literal references to DamageTypes, which needs cleaning up. Note also that the new Soviet F1 grenade isn't there.

Oh, I mentioned that a typo error in RO hid this bug: if you look at the same functionality in ROPawn you'll see it refers to 'ROStielGranateDamType' and 'ROF1GrenadeDamType'. Those are typos as the actual RO grenade DamageTypes don't have the 'RO' prefix - so this functionality was always skipped for grenades!

**Comment by handsm** [comment] 2016-10-29 15:03
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/83dd8a1e89ad108a3a5e64e35601d298cf8226c9.

Grenades still bounce off ragdolls, rather than simply passing through them, but the impact no longer moves the body.

**Closed by handsm** 2016-10-29 15:03 UTC
Labels: bug, infantry weapons
