### ISSUE TITLE
Sherman M4A3E3 (jumbo) commander optics can appear glitched out

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#602] opened 2016-08-25 19:18 UTC
Played Lutre-push yesterday as tanker, and I decided to use the Sherman A3E2 75 jumbo (last tank in the list) for the whole duration of the game.

I often experienced a problem with the optics (periscope) while sitting in the commander's position, and switching through different views. 
The problem is that the "periscope" view was often not showing properly, and instead I was taken to the "mini turret" (observation turret/cupola) that should actually come after periscope view.
Switching "up & down" through the different views fixed the problem for me. Can someone please test and confirm/deny this behavior?

**Comment by cmbasnett** [comment] 2016-08-25 22:01
I've seen this occur as well, but was never able to reproduce it 100%. It can also get into a weird state where you are in the vision-slit position but the periscope overlay is still visible. Will assign to @handsm. Thanks for the report.

**Comment by handsm** [comment] 2016-10-29 16:02
I can't recreate this, even simulating very bad network conditions (high ping and packet loss). The movement between view positions is always smooth and trouble free.

When a vehicle view position gets glitched, I have only ever seen it (or can imagine it happening) when the vehicle position is first entered. This bug is after that, when the player later moves up from the initial gunsight position - and I can't think of how that could happen.

I can't get anywhere with this unless I have reproduction steps.

**Comment by cmbasnett** [comment] 2017-02-10 20:06
Will close this since I haven't seen this in ages, can be re-opened if need be.

**Closed by cmbasnett** 2017-02-10 20:06 UTC
Labels: bug, vehicles
