### ISSUE TITLE
Client Crash Dealing With Tank Rounds

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#563] opened 2016-06-07 20:14 UTC
`Build RedOrchestra_Build_[2005-11-27_10.48]`

`OS: Windows NT 6.1 (Build: 7601)
CPU: GenuineIntel PentiumPro-class processor @ 3506 MHz with 4095MB RAM
Video: NVIDIA GeForce GTX 770 (5306)`

`General protection fault!`

`History: SetNetMode <- UActorChannel::ReceivedBunch <- (Actor DH_Flak88CannonShellHE) <- UChannel::ReceivedSequencedBunch <- Direct <- UChannel::ReceivedRawBunch <- DispatchDataToChannel <- BunchData <- UNetConnection::ReceivedPacket <- UNetConnection::ReceivedRawPacket <- UTcpNetDriver::TickDispatch <- UpdatePreNet <- ULevel::Tick <- (NetMode=3) <- TickLevel <- UGameEngine::Tick <- Level St-Clement <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 00000013 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free`

It also happened with DH_PanzerIVCannonShell, DH_PanzerIVCannonShell, but I'm sure it can happen to any of the subclasses.  This crash seemed to be happening when a tank projectile hit something.  Often I could hear it fire, then I'd GPF crash.  This is happening to everyone at least once an hour to multiple times a level.  Also I would notice it was usually one or two players that would crash, but sometimes it would crash 6 or so.

**Comment by handsm** [comment] 2016-06-08 15:25
Very likely caused by alterations to accommodate special net-culling BSP, although don't know exactly why/how. Will revert code tomorrow morning. Special BSP is being removed, so no need to handle.

**Comment by handsm** [comment] 2016-06-09 22:26
Projectiles code reverted to remove special BSP handling in commit: https://github.com/DarklightGames/DarkestHour/commit/186361fef38712f9d7d38ec81ba83f2e03efaf9b

This may resolve this bug. But on reviewing it, and the other recent crash bugs, I can't see any change that would possibly cause or cure such a crash. Like the other crash bugs, it may be a symptom of a wider build problem or whatever, as the actors & functions reported in the crash logs appear harmless.

**Comment by handsm** [comment] 2016-06-13 16:38
Been several full days without apparent recurrence of crash, including a busy tank-biased server, so I'm closing this. Don't think it was a code change that fixed it; think it was just general build problems in 7.0.0. Anyway ......

**Closed by handsm** 2016-06-13 16:38 UTC
Labels: crash
