### ISSUE TITLE
Mute certain sounds when round ends

### ISSUE THREAD

**Issue by kuopassa** [DarklightGames/DarkestHour#796] opened 2017-09-02 01:32 UTC
This is the age old problem when MG42 keeps spraying after a round is done. That annoying sound lasts until a new map is voted. Maybe it could be fixed? :-)

**Comment by cmbasnett** [comment] 2017-09-02 01:34
We've tried to fix this problem a number of ways over the years. In fact, it was one of the very first issue we logged in this system: (https://github.com/DarklightGames/DarkestHour/issues/57). In fact, I'll re-open and see if we can get it fixed for reals.

Duplicate of https://github.com/DarklightGames/DarkestHour/issues/57.

**Closed by cmbasnett** 2017-09-02 01:34 UTC
