### ISSUE TITLE
Trying to join a squad from the squad menu sometimes doesn't work or puts you in the wrong squad

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#728] opened 2017-07-05 23:58 UTC
Not sure how to reproduce this, but saw complaints about it in the first test.

**Comment by cmbasnett** [comment] 2017-08-18 00:38
Duplicate of https://github.com/DarklightGames/DarkestHour/issues/750.

**Closed by cmbasnett** 2017-08-18 00:38 UTC
Labels: bug
