### ISSUE TITLE
Some vehicles can be damaged by melee attacks

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#638] opened 2017-01-23 08:43 UTC
What it says on the tin. Sit around the Jeep, SdKfz 10/5 etc. and bayonet them into oblivion!

**Comment by handsm** [comment] 2017-01-30 21:10
Yeah, old RO issue. Easy fix. Will write up and commit in next couple of days.

**Comment by handsm** [comment] 2017-02-04 13:59
The TakeDamage() function in ROWheeledVehicle, which is the parent class for all vehicles, is commented "overloaded to prevent bayonet and bash attacks from damaging vehicles". But it doesn't actually do that, at least not directly.

What it does do is apply either a VehicleDamageModifier or an APCDamageModifier, based on whether the vehicle has bIsApc=true. Tanks and similar armoured vehicles get a different modifier in a more specialised subclass. The problem is that the RO damage types for bash and bayonet attacks, which are inherited by DH, both themselves inherit a VehicleDamageModifier of 0.1. So although damaged is considerably reduced, each melee attack still does 10% of normal damage to a vehicle.

Wouldn't have shown up as a problem in RO as all official vehicles were APCs or tanks or similar. There were no official soft skinned vehicles like we have. And looking at a common soft skinnned RO mod vehicle, the Soviet truck, it must have come up against the problem because they have fudged it by making the truck an APC (bash and bayo damage types have a zero APCDamageModifier).

Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/f7440d25c4654e831ef913654d40015d10dae93b by specifying a zero VehicleDamageModifier in the DH damage type calsses for bash and bayo attacks.

**Closed by handsm** 2017-02-04 13:59 UTC
Labels: bug, vehicles
