### ISSUE TITLE
MG34 & DP28 can appear to be "missing" on Macs

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#735] opened 2017-07-28 21:59 UTC
This has been reported multiple times, and we finally have a screenshot for it. No idea what the cause is.

![missing_mg34](https://user-images.githubusercontent.com/5035660/28737790-08203334-73a5-11e7-8b5e-5b4db03c9f71.jpg)

**Comment by handsm** [comment] 2017-08-01 14:32
Don't know what causes the problem, but I can see exactly what the problem is: the main weapon texture for material slot 2 (i.e. Skins[2]) isn't being drawn on the 1st person weapon mesh overlay. But you can see the secondary texture in material slot 3, which is the bipod texture. The bipod texture also skins the barrel, inside the perforated sleeve (not drawn here due to bug), which is why you can see that floating.

@cmbasnett : I only have a PC, so so you have a Mac you can use to check this? If so then can you check whether the other materials for the hands and sleeves are being drawn, so we know whether the problem is confined to the main weapon skin. Can't tell from this deployed screenshot, but if you reload you'll see whether the hands and arms are being drawn.

I can try some changes if it is only the main weapon slot. One unusual thing I have noticed about the MG34 main texture is that the shader material uses an opacity mask, which is rare among RO/DH weapons. It uses its own base/diffuse texture as the specified mask. Another weapon that's set up in the same way is the Soviet DP28 machine gun. I'd be interested for a Mac user to try that weapon to see if it produces a similar problem to the MG34. Could be no connection, but as they both have this rare setup it would be worth checking.

**Comment by cmbasnett** [comment] 2017-08-05 20:22
I believe people have reported that the DP-28 has the same issue. It could very well be the shader!

**Comment by handsm** [comment] 2017-08-06 08:07
In the Object class there's a PlatformIsMacOS() native function, plus similar for other OS. If the problem on Macs is the shader, should be able to use that to put in a fix for Mac players, while still keeping the specularity shader for the majority of players that use Windows, as it does make the first person weapon model look a lot better.

Do we have a Mac player who can test something for me?

**Comment by handsm** [comment] 2017-10-21 16:06
When researching another issue I came across lots of web references, mostly old, to UT2004 graphics problems affecting Macs and also Linux users. Wasn't this issue directly, but bug info said it concerned their use of OpenGL. Initial reports said that the maker of UT2004 had clearly stated they could not/would not be fixing the bug. More recent mentions are less clear, with some references to fixes or workarounds to some graphics bugs on Macs/Linux.

Probably related to this issue, although the specularity shaders for these two MGs work fine as a weapon skin, they cannot be specified as the HighDetailOverlay (HDO)for the weapon mesh, unlike all other weapons. The HDO is feature added in RO and handled by native code. It allows you to specify one main skin slot (for any mesh actor) and the HDO will be applied to it unless your game detail level is set to low, in which case it will revert to the default skin. But using it with these MGs causes the main weapon skin to become translucent, so they appear ethereal - not invisible as is happening on Macs, but certainly bugged.

I spent some time trying different ways of setting up the specularity shaders to get a complete HDO fix, which I thought would quite likely fix the more general bug on Macs, i.e. fixing whatever screws up the HDO would probably fix whatever screwing up the Mac. The two MGs have perforated a barrel sleeve, using alpha in the skin to create the holes. When used as the diffuse material in a specularity shader, the shader also needs to add an opacity mask for these holes to be maintained.  The problem is specifically caused by the diffuse texture being alpha. It seems the alpha-containing texture being used as the opacity mask is causing a kind of feedback. I tried making a separate non-alpha texture and using that only in the shader, but it wasn't possible by any combination to create a shader that worked and could be used as the HDO. One possibility is if a pure alpha/mask texture was made, just containing 100% transparent areas for the holes and 100% opacity for the rest, that may work as an opacity map.

**Comment by handsm** [comment] 2017-10-21 16:11
Probable workaround fix in https://github.com/DarklightGames/DarkestHour/commit/578cd7db1c04387dba2bccfc711b07e524264a15.

@cmbasnett  - can you please test and confirm this works ok on your Mac.

It's just a simple PlatformIsMacOS() check when the weapon spawns, if so switching the main weapon skin to the non-shader basic diffuse texture.

There is a similar PlatformIsUnix() check and I suspect this problem also affects and Linux users. So if anyone knows anyone who uses, or can access, a Linux setup then please let me know.

**Comment by AndrewTheel** [comment] 2018-04-21 17:00
Is this fixed? I'd like to close it if it is. @cmbasnett

**Comment by AndrewTheel** [comment] 2018-11-02 03:53
Assuming this is fixed.

**Closed by AndrewTheel** 2018-11-02 03:53 UTC
Labels: bug, infantry weapons
