### ISSUE TITLE
Several maps are unable to be played on a dedicated server

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#1105] opened 2020-01-24 09:35 UTC
Hattert, Lutremange Clash, Ten Aard are unplayable if hosted on a dedicated server.

Commit 243aa44098c9ac00c4a349ff0fa94dfd4bec0ff3 was the offending commit. I'm thinking it's something that was changed in `DHCharacters_anm.ukx` or `dhgear_anm.ukx`. I will run some tests and nail down exactly what the issue is.

---

@shiftycats: Hijacking the top message to add current information about this issue.

* There's no crash, clients stuck on the connection screen. Both server and client function normally otherwise.
* This happens with a specific set of maps. Most of these maps were unaltered, the biggest thing in common they have, is that they are all western front maps.
* Dedicated servers running on different machines (with identical settings) can have different broken maps, but otherwise are affected in the same manner.
* Maps work normally in single-player.
* Some changes to the map can either fix it or break it. Removing a certain actor can fix the map, but there's no pattern to it; it can be any actor.
* Some changes to the code can either fix or break some of the affected maps. Renaming a random class or changing a reference can alter the results, for example.
* The issue appeared after adding a bunch of new assets in [v9.5.0](https://github.com/DarklightGames/DarkestHour/compare/v9.4.5b...v9.5.0). It's possible that something broke before that and the effects only showed in v9.5.0.
* We tried to single out the problematic assets by adding them to the game one by one, but failed to come to any reliable conclusions, because we can't tell whether we fixed something or just "shuffled the cards". Some changes resulted in all the maps being fixed, but the bug would come back later.

### Logs
Server (stuck at `Open myLevel 10/10/20 18:40:19 192.168.2.20:62809`):
```
Log: Log file open, 10/10/20 18:36:51
Init: Name subsystem initialized
Init: Detected: Microsoft Windows NT 6.1 (Build: 7601)
Init: Version: 3339 (128.29)
Init: Compiled: Oct 22 2012 15:12:10
Init: Command line: DH-Ten_Aard_Clash.rom?game=DH_Engine.DarkestHourGame?MaxPlayers=64?Mutator=DH_AdminMenuMutator.DHAdminMenuMutator -log=DHServerLog_23923.log -mod=DarkestHourDev -ini=DarkestHourDev.ini
Init: Character set: Unicode
Init: Base directory: C:\Program Files (x86)\Steam\steamapps\common\Red Orchestra\System\
Init: Ini:..\DarkestHourDev\System\DarkestHourDev.ini   UserIni:..\DarkestHourDev\System\DarkestHourDevUser.ini
Init: Build label:  Build RedOrchestra_Build_[2005-11-27_10.48]
Init: Object subsystem initialized
Log: Executing Class Engine.ServerCommandlet
Log: Browse: DH-Ten_Aard_Clash.rom?Name=dirtybirdy?Class=Engine.Pawn?Character=G_Heer1?team=1?Sex=M?game=DH_Engine.DarkestHourGame?MaxPlayers=64?Mutator=DH_AdminMenuMutator.DHAdminMenuMutator
Log: Collecting garbage
Log: Purging garbage
Log: Garbage: objects: 83193->83187; refs: 1587774
Log: Game class is 'DarkestHourGame'
Log: STEAMAUTH : Steam auth system activation successful
Log: Bringing Level DH-Ten_Aard_Clash.myLevel up for play (32) appSeconds: 12.033000...
Log: (Karma): Autodetecting CPU for SSE
Log: (Karma): Using SSE Optimizations
ScriptLog: Loading Admins & Groups
ScriptLog: Kick and Ban Privileges Loaded
ScriptLog: Maps & Game Privileges Loaded
ScriptLog: Admins & Groups Management Loaded
ScriptLog: Extra Privileges Loaded
ScriptLog: Mutators DH_AdminMenuMutator.DHAdminMenuMutator
ScriptLog: GameInfo::InitGame : bEnableStatLogging False
Log: Defaulting to false
Log: Defaulting to false
WebAdmin: Loading Available Maps
WebAdmin: Loading Game Types
WebAdmin: DH_Engine.DHWebServerAdmin Initialized on port 8075
Log: STEAMAUTH : Sending updated server details - Darkest Hour Server 0 | 64
Log: STEAMAUTH : Connected to Steam Servers
Log: STEAMAUTH : VAC Security Disabled
Log: STEAMSTATS: SECURITY CHECK FAILED - Steam not Ready or Server not VAC Secure
NetComeGo: Open myLevel 10/10/20 18:40:19 192.168.2.20:62809
NetComeGo: Close TcpipConnection 192.168.2.20:62809 10/10/20 18:41:08
Log: Received ICMP port unreachable from 192.168.2.20:62809.  No matching connection found.
Exit: Preparing to exit.
Log: Purging garbage
Log: Unbound to Core.dll
Log: Unbound to Engine.dll
Exit: Game engine shut down
Log: STEAMAUTH : Shutting Down Server Steam Auth
Log: Unbound to ROEngine.dll
Log: Unbound to IpDrv.dll
Log: Unbound to Editor.dll
Log: Unbound to Fire.dll
Log: Unbound to XInterface.dll
Log: Unbound to XGame.dll
Log: Unbound to UWeb.dll
Log: (Karma): Level Karma Terminated.
Exit: Socket shut down
Log: Garbage: objects: 94656->0; refs: 1587774
Exit: Object subsystem successfully closed.
Exit: Exiting.
Log: FileManager: Reading 0 GByte 607 MByte 671 KByte 31 Bytes from HD took 2.125027 seconds (1.849027 reading, 0.276000 seeking).
Log: FileManager: 1.018992 seconds spent with misc. duties
Uninitialized: Name subsystem shut down
Uninitialized: Allocation checking disabled
Uninitialized: Log file closed, 10/10/20 18:42:53
```

Client (stuck after the `Log: Allocating 65536 byte dynamic vertex buffer.` line):
```
Log: Log file open, 10/10/20 18:40:15
Init: Name subsystem initialized
Init: Detected: Microsoft Windows NT 6.1 (Build: 7601)
Init: Version: 3339 (128.29)
Init: Compiled: Oct 22 2012 15:12:10
Init: Command line:  192.168.2.20 -mod=DarkestHourDev -log=DHLog_24589.log
Init: Character set: Unicode
Init: Base directory: C:\Program Files (x86)\Steam\steamapps\common\Red Orchestra\System\
Init: Ini:..\DarkestHourDev\System\DarkestHourDev.ini   UserIni:..\DarkestHourDev\System\DarkestHourDevUser.ini
Init: Build label:  Build RedOrchestra_Build_[2005-11-27_10.48]
Init: Object subsystem initialized
Localization: No localization: RedOrchestraLargeAddressAware.General.Start (int)
Log: 	igdumdim32.dll/Intel(R) HD Graphics 4000
Log: Game class is 'DHMainMenuGame'
Log: Bringing Level Entry.myLevel up for play (0) appSeconds: 3.069000...
Log: (Karma): Autodetecting CPU for SSE
Log: (Karma): Using SSE Optimizations
ScriptLog: GameInfo::InitGame : bEnableStatLogging False
Log: Browse: 192.168.2.20/Index.rom?Name=dirtybirdy?Class=Engine.Pawn?Character=G_Heer1?team=1?Sex=M
Log: Browse: Entry.rom?Name=dirtybirdy?Class=Engine.Pawn?Character=G_Heer1?team=1?Sex=M
Log: ALAudio: Using ALC_EXT_capture to record audio.
Warning: Failed to load 'NULL': Can't resolve package name
Warning: Failed to load 'Class None.': Can't resolve package name
Warning: Failed to load 'NULL': Can't resolve package name
Warning: Failed to load 'Class None.': Can't resolve package name
ScriptLog: New Player dirtybirdy id=20b300195d48c2ccc2651885cfea1a2f
Localization: No localization: RedOrchestraLargeAddressAware.General.Product (int)
Localization: No localization: RedOrchestraLargeAddressAware.General.Product (int)
Localization: No localization: RedOrchestraLargeAddressAware.General.Product (int)
Localization: No localization: RedOrchestraLargeAddressAware.General.Product (int)
Log: Opened viewport
Log: Enter SetRes: 1366x768 Fullscreen 1
Log: Using back-buffer format 22(32-bit)
Log: Using depth-buffer format 77(32-bit)
Log: Creating device
Log: xD3D9Helper::Init (QuadEmulation)
Log: POSTFX - TripPostFX::Init successful
Log: MultiSampling trying to use "0" samples-per-pixel, using "0" samples-per-pixel.
Log: Quality Levels, attempting to use "0", using a quality level of "0".
Log: Trying for 1 anisotropy, max is 16. Using 1.
Log: Startup time: 6.247000 seconds
Localization: No localization: RedOrchestraLargeAddressAware.General.Run (int)
Log: Precaching: Entry.LevelInfo0
Log: Static mesh batches: 0 vertex bytes, 0 index bytes
Log: Allocating 16384 byte dynamic index buffer.
Log: Finished precaching geometry in 0.035 seconds
Log: Finished precaching textures in 0.019 seconds
Log: Allocating 65536 byte dynamic vertex buffer.
ScriptLog: DHCinematicPlayer.ProgressCommand Cmd 'menu:DH_Interface.DHNetworkStatusMessage'  Msg1 'Cancelled Connect Attempt'   Msg2 ''
NetComeGo: Close TcpipConnection 192.168.2.20:7757 10/10/20 18:41:08
Exit: Socket shut down
Log: Defaulting to false
ScriptLog: DHBrowser_ServerListPageFavorites Spawned new ServerQueryClient 'Entry.ServerQueryClient'
Log: Defaulting to false
ScriptLog: DHBrowser_ServersList RECEIVED QUERYFINISHED NOTICE WITH ITEMCOUNT > 0!!! ITEMCOUNT:4 Info:0
Warning: DHBrowser_Footer Package.DHBrowser_Footer (Function DH_Interface.DHBrowser_Footer.InternalOnClick:006A) Accessed None 'PC'
Log: Resolving api.darklightgames.com...
Log: Resolved api.darklightgames.com (46.101.44.19)
Log: Unknown style requested none
Log: appRequestExit(0)
Localization: No localization: RedOrchestraLargeAddressAware.General.Exit (int)
Exit: Preparing to exit.
Log: Purging garbage
Log: Unbound to Window.dll
Log: Unbound to Core.dll
Log: Unbound to Engine.dll
Exit: Game engine shut down
Log: Unbound to WinDrv.dll
Log: POSTFX - TripPostFX::CleanUp
Exit: Windows client shut down
Log: Unbound to D3D9Drv.dll
Log: (Karma): Level Karma Terminated.
Log: Unbound to ROEngine.dll
Log: Unbound to IpDrv.dll
Log: Unbound to Editor.dll
Log: Unbound to Fire.dll
Log: Unbound to XInterface.dll
Log: Unbound to XGame.dll
Log: Unbound to UWeb.dll
Log: Unbound to ALAudio.dll
Log: Waiting for file streaming thread to finish...
Exit: OpenAL Audio subsystem shut down.
Log: Garbage: objects: 58200->0; refs: 0
Exit: Object subsystem successfully closed.
Exit: Exiting.
Log: FileManager: Reading 0 GByte 279 MByte 94 KByte 963 Bytes from HD took 1.307993 seconds (1.079993 reading, 0.228000 seeking).
Log: FileManager: 0.538997 seconds spent with misc. duties
Uninitialized: Name subsystem shut down
Uninitialized: Memory Allocation Status
Uninitialized: Curr Memory  0.219M /  5.121M
Uninitialized: Peak Memory  248.949M /  252.059M
Uninitialized: Allocs         852 Current /  6300843 Total
Uninitialized: Log file closed, 10/10/20 18:41:15
```

**Comment by cmbasnett** [comment] 2020-01-25 04:53
After another night of investigating, it was determined that the trouble started even further back, on commit a5ed430fd570972d264648c8a9b50654ad3d8321.

**Comment by cmbasnett** [comment] 2020-01-25 08:17
I have reason to believe that this was brought on, somehow, by the inclusion of several MN files, for example:
```
DH_MN_Weapons1st_tex.utx
DH_MN_Weapons3rd_tex.utx
DH_MN_WeaponPickupsSM.usx
```

The reason I believe this is that, if I move to the commit where these files were added (a5ed430) and *delete* the `DH_MN_Weapons1st_tex.utx` file, I get a huge amount of compile errors when trying to build the game for an unrelated set of files:

![image](https://user-images.githubusercontent.com/5035660/73118240-72681980-3f06-11ea-82aa-e0ea5245fdc4.png)

I have no idea what is going on here. My feeling is that there is some sort of naming conflict that is happening deep in the engine code, but I honestly have nothing to back this up other than a hunch.

**Comment by shiftycats** [comment] 2020-01-26 07:25
Seems like the compiler fails the entire package if it contains a broken reference. In this case, `DH_Weapon3rd_anm.BHP_3rd` refers to a removed MN package, which results in a hail of unresolved references that point to `DH_Weapon3rd_anm`.

**Comment by GarlicAAZ** [comment] 2020-01-26 13:05
did you guys try to just remove all new weapons from those maps and try if they work?
i think only BHP and m1928 thompson have anything to do with any MN references, so if the problem is in them then then it should fix them

**Comment by shiftycats** [comment] 2020-01-26 14:31
Deleting certain things from maps makes them work, but none of those things are related to BHP or anything specifically. There's no apparent pattern to it, no nothing.

I can confirm though, that removing the `DH_MN_Weapons1st_tex.utx` package (and clearing out all the references to it) allows the maps to load.

**Comment by AndrewTheel** [comment] 2020-01-26 16:28
Hmm this would be a new issue the, never encountered an issue just like this one. I have encountered an issue that broke maps, but it was some default property format issue (I think inside a role class).

**Comment by cmbasnett** [comment] 2020-01-26 21:26
@shiftycats Did deleting the `DH_MN_Weapons1st_tex.utx` package work on the head of the master branch? If so, fixing this should be relatively easy, we'd just need to manually re-import any textures we used from that package.

**Comment by GarlicAAZ** [comment] 2020-01-26 21:32
> I can confirm though, that removing the DH_MN_Weapons1st_tex.utx package (and clearing out all the references to it) allows the maps to load.

...so why not just remove the BHP and M1928 which are the only things related to that package?

**Comment by shiftycats** [comment] 2020-01-27 01:01
> Did deleting the `DH_MN_Weapons1st_tex.utx` package work on the head of the master branch?

Yes.

I've narrowed it down to MAB28. Removing the package wasn't necessary; commenting out these refs in the `DH_MAB38Weapon` is sufficient:
```
HighDetailOverlay=Shader'DH_MN_Weapons1st_tex.SMG.Ber1Tex_S'
Skins(0)=Shader'DH_MN_Weapons1st_tex.SMG.Ber1Tex_S'
```

**Comment by cmbasnett** [comment] 2020-01-27 02:07
That is very strange. Perhaps there some sort of screwy reference nonsense going on in the shader?

Also, it's odd that the `Skins` array is referencing the `Shader` itself. I don't believe this is the way any of the other weapons work. I have experienced some very strange stuff happen with regards to the `HighDetailOverlay` stuff. Perhaps fix that Skins array to just reference the diffuse?

If that doesn't fix it, the MAB38 should be given its own texture package with remade-from-scratch shaders. Ideally, everything gets moved out of that MN package eventually, but for a first "light touch" fix, just doing that should suffice.

**Comment by shiftycats** [comment] 2020-01-27 02:58
> Perhaps fix that Skins array to just reference the diffuse?

This did the trick.

**Comment by AndrewTheel** [comment] 2020-01-27 17:33
Random maps broken because of some un-referenced package referencing a shader... And it was discovered, congrats!

**Comment by shiftycats** [comment] 2020-01-28 12:53
Alright, commits 1f70a75e57279e89c9d9d0d7d386491f0b0cfcf2 and d6e33bd7ca6d3300793c63748c453371ed85feeb fixed the following maps:
```
DH-Cambes-En-Plaine_Clash 
DH-Lutremange_Clash
DH-Putot-en-Bessin_Advance 
DH-Ten-Aard_Clash
``` 

Now `DH-Hattert_Clash` is broken again :woman_facepalming:.

**Comment by shiftycats** [comment] 2020-01-28 13:52
Clearing out the `Texture'DH_BHP_tex.BHP.BHP'` reference in `DH_WeaponPickup.Weapons.BHP` fixes Hattert.

**Comment by shiftycats** [comment] 2020-01-30 08:57
Related commit: 7ffe7224256fd3303935dab8c7a1f3676066d746

**Comment by shiftycats** [comment] 2020-03-30 14:34
It's back! Something introduced after v9.6.3 broke Hedgerow Hell and Nuenen. To make things more exciting, i can't replicate this on my local server. The maps only freeze official servers.

Cambes-en-Plaine is affected as well, though this happened at some point between v9.5.5 and v9.6.3, and i can replicate it locally.

**Comment by shiftycats** [comment] 2020-04-01 19:52
These effects introduced in 2547c9f76eb8ab5a856aa0685421985d356b1a27 cause Cambes-en-Plaine to fail: 
* [`DHTurretFireEffect`](https://github.com/DarklightGames/DarkestHour/blob/2547c9f76eb8ab5a856aa0685421985d356b1a27/DH_Effects/Classes/DHTurretFireEffect.uc)
* [`DHVehicleDamagedEffect`](https://github.com/DarklightGames/DarkestHour/blob/2547c9f76eb8ab5a856aa0685421985d356b1a27/DH_Effects/Classes/DHVehicleDamagedEffect.uc)

The issue is not in their contents though; from what it seems, they just don't like to extend `VehicleDamagedEffect`. Probably has something to do with latter being a native class.

**Comment by shiftycats** [comment] 2020-04-02 06:46
Reverting hatch fire stuff (6317d77f7e569d0e7f240b4a63d2b806b2fb9ca0) worked when applied to `v9.6.3`, but on `v9.7.1` it has no effect. In fact, the reversion also broke Hedgerow Hell on my local server (it only appeared to be broken on live servers).

**Comment by AndrewTheel** [comment] 2020-04-02 07:19
Okay so I'm just gonna make a suggestion here, take it with a grain of salt. But what you should do is take one of the servers, just pick one of the 2 infantry servers (server #2). Copy it's .ini file and then delete it. Launch the server (it will generate a new one). Then close it down again and edit the new .ini file with some basic required settings. Then see if that server still has those crashes on those maps. Otherwise I suspect something might be happening with the server files generating. Like client files are fine, but the ones created for dedicated server via steam might be the issue specifically. The underlying cause could be some naming mishap, which does not present itself in the client files. I'm starting to strongly feel this is a naming mishap. Like some new texture, asset, class, effect, etc is named the same as something the level has or uses. If you can narrow down the exact class, then you could do a all-files search for that classname to see what files it returns. If for instance it returns a texture file or a map file, you probably found the problem.

**Comment by shiftycats** [comment] 2020-04-03 07:36
Removing `.ini` files on live server fixed `Hedgerow Hell`, but had no effect on other maps.

It appears that commit efe5800cbcc646f6e11ad7640899ea7b3a8329a2 has corrupted `Lutremange`.

**Comment by AndrewTheel** [comment] 2020-04-03 12:46
Why did it fix HH? that answer might reveal something you guys aren't noticing.

**Comment by shiftycats** [comment] 2020-04-03 13:35
Clearing out this URL in `DarkestHour.ini` fixes HH:
```
[IpDrv.HTTPDownload]
RedirectToURL=http://darkesthour.darklightgames.com/fdl/
```

**Comment by AndrewTheel** [comment] 2020-04-03 13:42
reeeeee, FDL

**Comment by shiftycats** [comment] 2020-04-03 13:46
Does that reveal anything?

**Comment by AndrewTheel** [comment] 2020-04-03 13:52
Maybe. Explain in chat.

**Comment by AndrewTheel** [comment] 2020-04-20 06:01
Open myLevel 04/20/20 00:54:06 10.0.0.64:58658
STEAMAUTH : Game Server SendUserConnectAndAuthenticate returned error (10.0.0.64:58658)
Close TcpipConnection 10.0.0.64:58658 04/20/20 00:54:06

**SendUserConnectAndAuthenticate returned error**

**Comment by AndrewTheel** [comment] 2020-04-20 07:26
`Log: Couldn't find outstanding request for rules from 185.38.151.245:7778
Log: Couldn't find outstanding request for rules from 185.38.151.245:7778
Log: Couldn't find outstanding request for rules from 185.38.151.35:7758
Log: Couldn't find outstanding request for rules from 185.38.151.35:7758`

**Comment by shiftycats** [comment] 2020-06-15 18:54
Narrowed down to changes made in commits 9c055a584b4b097ff1e3843b831c5156f6931058 and 8b5a7c89612f443b062c0879b17c4365180d4a3b.

**Comment by shiftycats** [comment] 2020-07-29 09:20
Ten Aard and Juno Beach are removed from the roster due to freezing the servers.

**Comment by shiftycats** [comment] 2020-10-11 03:40
Here are the logs after attempting connection with all `Suppress` entries removed from the `ini` file (as suggested in https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1602293629/4#4).

### Server
[**Full log**](https://www.dropbox.com/s/oi7yoq7p63g7lxi/DHServerLog_29177.log?dl=0)
```
DevNet: NotifyAcceptingConnection: Server myLevel accept
NetComeGo: Open myLevel 10/11/20 03:28:58 192.168.2.20:58999
DevNet: NotifyAcceptingChannel Control 0 server Level DH-Ten_Aard_Clash.myLevel: Accepted
DevNet: Level server received: HELLO REVISION=0 MINVER=3180 VER=3339 STEAMID=76561198043869714
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=0 BLOB=14000000feb4212772ea206512b2fb0401001001afd4815fb8000000380000000400000012b2fb0401001001000500000783fe6d1402a8c0000000008d657f5f0d159b5f01003f00000001000a05000000000000b89e40199c6500e8c67c9c64fac3b1dd6dc28338cbf6fb09f330839a8c0d5550b49a9ba5098a3bffa6ce8778
DevNet: STEAMAUTH : Server recieved client blob 212 0 - 14000000feb4212772ea206512b2fb0401001001afd4815fb8000000380000000400000012b2fb0401001001000500000783fe6d1402a8c0000000008d657f5f0d159b5f01003f00000001000a05000000000000b89e40199c6500e8c67c9c64fac3b1dd6dc28338cbf6fb09f330839a8c0d5550b49a9ba5098a3bffa6ce8778
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=1 BLOB=92e5f24365d11f021fbaeb1d7e584fdfc49d463934aa41dfe6114ec29464995158e131720c4737bbb9ac120cde6fcc7828cca40129aa5b980ca8488981180ff299167c1028f11839c88aa92359ca6628ad7128b40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 1 - 92e5f24365d11f021fbaeb1d7e584fdfc49d463934aa41dfe6114ec29464995158e131720c4737bbb9ac120cde6fcc7828cca40129aa5b980ca8488981180ff299167c1028f11839c88aa92359ca6628ad7128b40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=2 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 2 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=3 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 3 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=4 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 4 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=5 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 5 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=6 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 6 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=7 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 7 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=8 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 8 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=9 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 9 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=10 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 10 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=11 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 11 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=12 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 12 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=13 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 13 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=14 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 14 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMCLIENTBLOB SIZE=212 CHUNK=15 BLOB=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : Server recieved client blob 212 15 - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DevNet: STEAMAUTH : chunk < 32 && blobk.Len() > 0
DevNet: STEAMAUTH : invalid index >= 128
DevNet: Level server received: STEAMTICKET SIZE=1 CHUNK=0
DevNet: Level server received: STEAMTICKET SIZE=1 CHUNK=1
DevNet: Level server received: STEAMTICKET SIZE=1 CHUNK=2
DevNet: Level server received: STEAMTICKET SIZE=1 CHUNK=3
Log: STEAMAUTH : Sending updated server details - Darkest Hour Server 0 | 64
Log: STEAMAUTH : Connected to Steam Servers
Log: STEAMAUTH : VAC Security Disabled
Log: STEAMSTATS: SECURITY CHECK FAILED - Steam not Ready or Server not VAC Secure
DevNet: Level server received: AUTH HASH=1990084c866612acb11a64c4730001df GM=995fd1aaa75247718dc6df903f493bae8d943f8d85ffbf7e610ffbfb426375227ed3737473b573767eb771e87429789a7d1b7f2c742d739ed9bc5c30773ed39a6f18 USERNAME= PASSWORD=
DevNet: Level server received: NETSPEED 10000
DevNet: Client netspeed is 10000
DevNet: Level server received: LOGIN RESPONSE=1466229894 URL=Index.rom?Name=dirtybirdy?Class=Engine.Pawn?Character=G_Heer1?team=1?Sex=M
DevNet: Login request: Index.rom?Name=dirtybirdy?Class=Engine.Pawn?Character=G_Heer1?team=1?Sex=M
DevNetTraffic: Control channel bunch overflowed
DevNetTraffic: Control channel bunch overflowed
DevNetTraffic: Control channel bunch overflowed
DevNetTraffic: Control channel bunch overflowed
DevNetTraffic: Control channel bunch overflowed
DevNetTraffic: Control channel bunch overflowed
DevLoad: Loading object 'IpDrv.HTTPDownload'  class 'Class'
DevLoad: Loading object 'Engine.ChannelDownload'  class 'Class'
DevNetTraffic: Control channel bunch overflowed
DevNetTraffic: Control channel bunch overflowed
Log: STEAMAUTH : Accepted Client : SteamID [1:83603986] (76561198043869714)
```

### Client
[**Full log**](https://www.dropbox.com/s/i9ivx81hws5g318/DHLog_29327.log?dl=0)
```
DevLoad: Loading object 'ini:Engine.Engine.NetworkDevice'  class 'Class'
Init: WinSock: Socket queue 32768 / 32768
DevNet: Game client on port 0, rate 20000
```

**Comment by shiftycats** [comment] 2020-10-11 03:50
https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1375711942/72#72
According to this post, `DevNetTraffic: Control channel bunch overflowed` messages might indicate that we have too many ServerPackages.

**Closed** 2020-10-11 13:04 UTC
Labels: bug, live build
