### ISSUE TITLE
Players can appear to fall through the map when spawning on deploy vehicles

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#493] opened 2015-12-28 22:57 UTC
This is actually a visual glitch. The player will never actually die from falling through the level. The camera just falls and falls endlessly. To fix it, you just need to switch positions or exit the vehicle. I can only speculate as to what the cause is. Very difficult to reproduce, probably only occurs when there are lots of players.

![2015-12-28_00004](https://cloud.githubusercontent.com/assets/5035660/12078266/ddb9b26c-b1bf-11e5-8bad-8f2757569d76.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/t2bfDEZ6)

**Comment by dynamittt** [comment] 2016-01-31 19:02
Similar bug often seen in RO and DH (prev. version) when riding a vehicle as **passenger**:
player camera would appear not to be moving with the vehicle, but stay in one spot. Fixed with the  change of passenger position.

**Comment by handsm** [comment] 2016-06-09 11:31
I recall the passenger bug mentioned by dynamittt was caused by the player trying to switch to an ineligible vehicle position, i.e. an infantry tank rider pressing 1, 2 or 3 keys and being unable to switch to a tanker-only position. The fix was to do clientside checks that the player was switching to an eligible position, before calling the switch position functionality on the server.

But with deploy vehicles, the problem is usually replication timing. The vehicle is often some way away and the player's client may not have the various vehicle actors, because before he spawns into the vehicle, it is no net relevant. When the player deploys into it, the player suddenly receives all the vehicle actors by replication. These arrive in a jumbled order, with time delays dictated by the saturation of the network at that moment.

We have already built in many safegaurds in several places to handle these replication timing problems, which especially plague deploy vehicles, but can affect all vehicles. Basically, we use the client receiving various vehicle-related actors as a trigger to do certain things, only when those actors are received by the net client. We probably need another one ......

**Comment by handsm** [comment] 2017-07-10 16:58
This was reported way back and there may have been changes since. Is it still a problem?

**Comment by cmbasnett** [comment] 2017-07-10 18:41
I've not seen this since the 6.0 beta testing days, so I'll call it fixed.

**Comment by AndrewTheel** [comment] 2017-07-10 18:42
Agreed I haven't seen it either, if I "do see it" its because of server lag, it just looks like I feel through but then the server updates me and I didn't actually fall through.  I think its save to close.

**Closed by AndrewTheel** 2017-07-10 18:42 UTC
Labels: bug, deployment
