### ISSUE TITLE
Satchels have no effect on obstacles (such as fences)

### ISSUE THREAD

**Issue by kasinobonuksia** [DarklightGames/DarkestHour#1006] opened 2018-12-05 22:37 UTC
Shouldn't destroyable fences (and barb wire) be destroyable with satchel charges as well? ;-)

**Comment by cmbasnett** [comment] 2018-12-06 01:53
This is a known bug with *some* of the wooden fences. The root cause is that the origin of the fences are technically under the ground, so the ground is absorbing the hit.

**Comment by AndrewTheel** [comment] 2018-12-06 19:51
This can easily be resolved by tapping into the "explode" function and doing a radius actors check for obstacles and damaging them based on distance.

**Comment by AndrewTheel** [comment] 2018-12-13 01:46
Duplicate of https://github.com/DarklightGames/DarkestHour/issues/1006

**Closed by AndrewTheel** 2018-12-13 01:46 UTC
