### ISSUE TITLE
Artillery damage precedes explosion emitter

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#406] opened 2015-09-26 03:52 UTC
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

Artillery explosions have a very noticeable ~0.5 second disconnect from when damage and karma forces are applied on players and the actual emitter spawns.

This is particularly noticeable when you see a friend or foe's body go flying limbless into the air apropos of nothing only to see the explosion emitter manifest long after the damage is already done.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/407

**Comment by handsm** [comment] 2015-12-23 08:32
I'll take this one, if you have no objection. I seem to have become Mr Projectile ! :)

Interesting comment re "why projectile?". Probably a fair point. From memory, I think it already does a downwards trace to get near the terrain, then spawns the proj there & lets it 'launch' downwards. I need to re-base the proj classes for 7.0 and the arty shell is 1 of 2 that don't extend ROBallisticProjectile, so if we can remove it as a proj, it could help me get from 2 potential DH base proj classes down to only 1, which would be ideal.

**Comment by handsm** [comment] 2016-06-15 14:39
Ok, investigated the arty classes and I see the problem. Timing of explosion is based on the duration of the 'close sound' (the scream of the incoming shell). A random choice of close sounds is made for each shell - and this random choice is done independently on server and each net client ! Sound durations vary from 1.14 to 2.22 seconds, so the difference in explosion timing between server and client can be a bit over a second.

Damage happens on the server, so you see/hear the effects of that damage on other players or objects based on the server's explosion timing. But the explosion effects are played locally by the client, based on its own timing, so it may be over a second later (or earlier).

The simple solution appears to be to set the random close sound on the server only, then replicate that sound to each relevant client. Or for greater network efficiency, I'd implement that as a replicated byte representing the index of the selected close sound. That should solve it. As the arty shell is a bNetTemporary actor, meaning it gets torn off as soon as it replicates, we need to make sure the close sound index gets set by the server during its own actor initialisation, before the actor replicates. It needs to be earlier than currently.

I looked at whether arty shells as separate projectiles could be eliminated. The basic idea would be to replace the shell actors with a shells array in the DHArtillerySpawner actor, where each arty round becomes a member of that array. And then have the server replicate each shell's impact location to clients, so they could spawn explosion effects locally.

But the problem is that each projectile actor needs to run 2 sequenced timers, based on random sound selection, and play 3 sounds (distant, close and explosion). So if we didn't have projectile actors, the server's DHArtillerySpawner would have to try to do all that for many arty rounds, all overlapping at different times. To be practical, I think it it would have to spawn separate actors for each round anyway, to handle the timing and broadcast sounds, so a projectile is probably as good as any other actor. And as it's a torn off actor, the replication is as efficient as it can be.

The DHArtillerySpawner actor is currently replicated to clients, but should be a server only actor. None of its functions even run on a client. So replication of this actor is pointless and can be removed, saving replication and a net channel. Note that even if we managed to eliminate projectile actors, handling all timing and broadcasting all sounds on the server, we would then need to retain the DHArtillerySpawner as a fully replicated actor so the server could replicate an impact location to each client, triggering them to spawn explosion effects. And all sounds would have to broadcast over the network, where with projectiles the sounds are played locally.

I also note that every projectile actor spawns a separate actor just to play its close sound on. But the timer system appears to stop any overlay between distant, close and explosion sounds, so I think it will be possible to avoid spawning this extra actor for each shell.

Overall, the arty shell class is obfuscated by badly named variables and functions and some less than clear logic flow. This can easily be improved for much greater clarity.

**Comment by handsm** [comment] 2016-10-29 15:14
For info I completed this as part of a rationalisation of projectile parent classes, which included a few small fixes and improvements. I stashed all that work when I thought a release was imminent a while back. I'll dig it out, refresh myself on it, but better to do that just after 7.1 release, I think.

**Comment by handsm** [comment] 2016-11-30 12:48
1st stage towards fix in commit https://github.com/DarklightGames/DarkestHour/commit/30a7ae0aeff2d4c6ef8188eb6638aae20635018f:

I've deprecated the confusing & badly written ROArtilleryShell class. DHArtilleryShell now contains everything it did and directly extends the base Projectile class. Renamed several variables and functions for clarity (one bad example: bAlreadyPlayedFarSound flagged that the CLOSE sound had already been played, not the DISTANT sound!). The basic functionality is the same, but have refactored all of it for clarity, as overall it was pretty obfuscated - now it is easy to follow.

Also includes a fix for problems/confusion in RO class re making the shell visible, stemming from the fact that an arty shell can spawn several metres above the ground a second or 2 before it actually begins to fall. That's because if the close/incoming sound is longer than the shell's flight time to impact, the shell is 'held' and not dropped until its impact will coincide with the end of the close sound. So if the shell is made visible at that point you see a hanging shell.

RO 1st tried hiding the shell with bVisible=false, but that stopped it replicating. So they ended up hacking it by setting the DrawScale to 0.001 so the hanging shell couldn't be seen. I have simply started the shell with a DrawType of none, then set the DrawType to StaticMesh when the shell gets dropped from its hanging position (so it is invisible until then). Having a DrawType of none makes it invisible but doesn't prevent replication of the shell actors to net clients.

And as the incoming shell is now visible I have updated it from a panzerfaust warhead to a large shell. Now, if you are looking directly at an incoming arty strike, you will just see a the large HE shells flashing down to impact.

**Comment by handsm** [comment] 2016-11-30 12:49
Fixed implemented in commit https://github.com/DarklightGames/DarkestHour/commit/9c55a0875f67094f2e23c198aec464a6df7a35e1.

I've replaced the variable SelectedCloseSound with a new replicated byte CloseSoundIndex. This is selected only by the server in the shell's initialisation and replicated to all net clients. All close/incoming sounds - and crucially the projectile timing associated with that - is now based solely on this replicated index no. So server and all clients are now in synch.

**Comment by handsm** [comment] 2016-12-02 17:47
Further arty functionality improvements & tidy up in commit https://github.com/DarklightGames/DarkestHour/commit/6616a03fbc4d3055afdc7bde6bd02e2cd37a004e. Main points:

- Got rid of the separately spawned SoundActor for each shell, just to play the close/incoming sound. Just had to remove a bNoOverride option from the close sound, as that was often stopping the slightly overlapping explosion sound from playing (suspect that was reason for separate SoundActor).
- Made DistantSound a single sound instead of a static array as there is only 1 distant sound (all 4 array entries were the same), & reduced CloseSound static array from 4 to 3 size as there are only 3 sounds (4th was a duplicate).
- Now spawn the invisible arty spawner actor directly on the arty strike location, not above it, with shells spawned a standard 20m above strike location, instead of using the map's NorthEastBounds for the height (which could be a bit random & perhaps problematic if too low).
- Stopped shells from being always network relevant to the calling arty officer, so if he dies or otherwise moves well away from the arty strike, the server can determine whether the shells are still relevant to him (before they always were).
- Removed a fair bit of redundancy & unnecessary instance variables.

With the separate SoundActor gone, I was thinking again about the possibility of getting rid of arty shells altogether and instead having the server-only arty spawner determine the impact location of shells & tell each client to spawn impact/explosion sounds/effects there. So replacing shells with an array of pseudo-shells  in the spawner. Still problematic, I think. But I thought of another way that I think will achieve 90% of the benefits, which would be avoiding having loads of arty shell actors replicate to net clients:

My idea is to make the spawner a replicated actor (again), have the server actor create an array of randomly selected shell locations & timing delays (the array of 'pseudo-shells'), replicate that info to clients, then have clients spawn their own local copies of the shells. The server would still spawn shells and they would handle damage, but it wouldn't have to replicate loads of shell actors to clients.  The client versions of the shells would be there for sound & visual effects, which is the same as any client version of a projectile and the same as it is now.

Given that an arty strike is typically around 50 shells and can be well over 100, and that actor replication is a pretty heavyweight network load, I think replication/net loading would be significantly reduced. Haven't gone through this in any detail but will probably work. But .... another issue for another day. This reported bug is fixed, I believe, so closing this issue.

**Closed by handsm** 2016-12-02 17:47 UTC
Labels: bug, gameplay
